-- 58 new builtin items from the icon asset drop. Pricing by
-- category: cheap throwables (food / silly junk) at 20-100,
-- medium gifts / tools at 100-500, premium gear / magic at
-- 500-5000, legendary armor at 6000+. All items support
-- /give /throw /drop with category-appropriate templates.
-- Order slots are grouped by category for shop legibility:
--   200-219 food / drinks
--   250-279 silly / joke
--   300-349 tools / utility
--   350-379 romance / gifts (including kaal_dragon_plushie)
--   380-419 magic
--   420-449 tabletop / treasure
--   450-479 precious metals
--   500-599 armor
--
-- Three asset filenames carry typos in the underlying PNG
-- (chromtic_legendary_armor, enagement_ring, paerlescent_shell);
-- the slug matches the filename so the icon_url resolves, but
-- display names are spelled correctly so chat lines / shop
-- cards read clean. `ComfyUI_00207_.png` is not registered —
-- its filename doesn't describe an item, so it stays
-- orphaned until an admin renames the asset.

INSERT INTO `items` (`key`, `name`, `name_plural`, `description`, `icon_url`, `price`, `stack_limit`, `give_messages_json`, `throw_messages_json`, `drop_messages_json`, `aliases_json`, `is_builtin`, `order`) VALUES
  (
    'apple',
    'Apple',
    'apples',
    'A crisp red apple. Doctor-repellent.',
    '/assets/items/apple.png',
    25,
    99,
    '["{sender} hands {target} {num} {item_name}.","{sender} offers {target} {num} {item_name}."]',
    '["{sender} pelts {target} with {num} {item_name}!","{sender} hurls {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}''s head. *bonk*"]',
    '["fruit"]',
    1, 200
  ),
  (
    'pear',
    'Pear',
    'pears',
    'A ripe pear. Sweeter than its cousin.',
    '/assets/items/pear.png',
    30,
    50,
    '["{sender} offers {target} {num} {item_name}.","{sender} hands {target} {num} {item_name}."]',
    '["{sender} lobs {num} {item_name} at {target}.","{sender} pelts {target} with {num} {item_name}."]',
    '["{sender} drops {num} {item_name} on {target}. Squish."]',
    '[]',
    1, 201
  ),
  (
    'tomato',
    'Tomato',
    'tomatoes',
    'A ripe tomato. The classical projectile.',
    '/assets/items/tomato.png',
    30,
    50,
    '["{sender} hands {target} {num} {item_name}.","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! Audience approves.","{sender} pelts {target} with {num} {item_name}.","{sender} flings {num} {item_name} at {target}. Stage-worthy."]',
    '["{sender} drops {num} {item_name} on {target}. Splat."]',
    '["rotten tomato"]',
    1, 202
  ),
  (
    'onion',
    'Onion',
    'onions',
    'An onion. Layered, fragrant, weep-inducing.',
    '/assets/items/onion.png',
    25,
    50,
    '["{sender} hands {target} {num} {item_name}. Eyes water in anticipation.","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}.","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. The smell lingers."]',
    '["bulb"]',
    1, 203
  ),
  (
    'mushroom',
    'Mushroom',
    'mushrooms',
    'A plump mushroom. Probably safe to eat. Probably.',
    '/assets/items/mushroom.png',
    30,
    30,
    '["{sender} hands {target} {num} {item_name}.","{sender} offers {target} {num} {item_name}. \"Trust me.\""]',
    '["{sender} flings {num} {item_name} at {target}.","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. Sprouts on impact."]',
    '["fungus","shroom"]',
    1, 204
  ),
  (
    'fish',
    'Fish',
    'fish',
    'A whole fish. Quite fresh. Mostly.',
    '/assets/items/fish.png',
    60,
    20,
    '["{sender} hands {target} {num} {item_name}. \"For dinner.\"","{sender} offers {target} {num} {item_name}."]',
    '["{sender} slaps {target} with {num} {item_name}!","{sender} hurls {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. The smell will linger for weeks."]',
    '["trout","smelly fish"]',
    1, 205
  ),
  (
    'cheese_wheel',
    'Cheese Wheel',
    'cheese wheels',
    'A whole wheel of cheese. Aged. Heavy. Slightly intimidating.',
    '/assets/items/cheese_wheel.png',
    150,
    5,
    '["{sender} hands {target} {num} {item_name}.","{sender} rolls {num} {item_name} over to {target}."]',
    '["{sender} bowls {num} {item_name} at {target}!","{sender} hurls {num} {item_name} at {target}. Cheesy impact."]',
    '["{sender} drops {num} {item_name} on {target}. Foot, flattened."]',
    '["cheese","wheel of cheese"]',
    1, 206
  ),
  (
    'loaf_of_bread',
    'Loaf of Bread',
    'loaves of bread',
    'A crusty loaf of bread. Still warm.',
    '/assets/items/loaf_of_bread.png',
    50,
    10,
    '["{sender} hands {target} {num} {item_name}.","{sender} tears off and offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}.","{sender} clobbers {target} with {num} {item_name}."]',
    '["{sender} drops {num} {item_name} on {target}. *thunk*"]',
    '["bread","loaf"]',
    1, 207
  ),
  (
    'turkey_leg',
    'Turkey Leg',
    'turkey legs',
    'An entire turkey leg. Renaissance-fair grade.',
    '/assets/items/turkey_leg.png',
    100,
    10,
    '["{sender} hands {target} {num} {item_name}. Feast time.","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} bonks {target} with {num} {item_name}."]',
    '["{sender} drops {num} {item_name} on {target}. Greasy."]',
    '["drumstick","meat"]',
    1, 208
  ),
  (
    'bowl_of_stew',
    'Bowl of Stew',
    'bowls of stew',
    'A bowl of hearty stew. Steam, included.',
    '/assets/items/bowl_of_stew.png',
    80,
    10,
    '["{sender} hands {target} {num} {item_name}. Mind the heat.","{sender} ladles out {num} {item_name} for {target}."]',
    '["{sender} flings {num} {item_name} at {target}! Hot, messy, hot.","{sender} hurls {num} {item_name} at {target}."]',
    '["{sender} dumps {num} {item_name} on {target}. A laundromat awaits."]',
    '["stew","soup"]',
    1, 209
  ),
  (
    'honeypot',
    'Honeypot',
    'honeypots',
    'A clay pot of golden honey. Bees not included.',
    '/assets/items/honeypot.png',
    200,
    5,
    '["{sender} hands {target} {num} {item_name}. Sticky gift.","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! Sticky impact.","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} pours {num} {item_name} on {target}. They''re going to find this everywhere."]',
    '["pot of honey","honey"]',
    1, 210
  ),
  (
    'candies',
    'Candies',
    'candies',
    'An assortment of colorful candies. Suspiciously sticky.',
    '/assets/items/candies.png',
    30,
    99,
    '["{sender} hands {target} {num} {item_name}.","{sender} offers {target} {num} {item_name}. Trick OR treat."]',
    '["{sender} pelts {target} with {num} {item_name}!","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. Sticks to everything."]',
    '["candy","sweets"]',
    1, 211
  ),
  (
    'coffee_in_mug',
    'Coffee',
    'mugs of coffee',
    'A steaming mug of coffee. Civilization, distilled.',
    '/assets/items/coffee_in_mug.png',
    80,
    10,
    '["{sender} hands {target} {num} {item_name}.","{sender} slides {num} {item_name} across the table to {target}."]',
    '["{sender} flings {num} {item_name} at {target}! Splashy.","{sender} hurls {num} {item_name} at {target}."]',
    '["{sender} spills {num} {item_name} on {target}. The grounds will be EVERYWHERE."]',
    '["coffee","caffeine","mug of coffee"]',
    1, 212
  ),
  (
    'tea_in_teacup',
    'Tea',
    'teacups of tea',
    'A delicate teacup of properly steeped tea. Saucer included.',
    '/assets/items/tea_in_teacup.png',
    80,
    10,
    '["{sender} pours {target} {num} {item_name}.","{sender} hands {target} {num} {item_name}. Pinky out."]',
    '["{sender} flings {num} {item_name} at {target}! Most uncivil.","{sender} hurls {num} {item_name} at {target}."]',
    '["{sender} spills {num} {item_name} on {target}. Saucer survives. Briefly."]',
    '["tea","teacup","brew"]',
    1, 213
  ),
  (
    'wine_in_wineglass',
    'Wine',
    'wineglasses of wine',
    'A glass of deep red wine. Aged, allegedly.',
    '/assets/items/wine_in_wineglass.png',
    200,
    5,
    '["{sender} pours {target} {num} {item_name}.","{sender} hands {target} {num} {item_name}. Cheers."]',
    '["{sender} flings {num} {item_name} at {target}! Vintage ruined.","{sender} hurls {num} {item_name} at {target}."]',
    '["{sender} spills {num} {item_name} on {target}. The carpet will not recover."]',
    '["wine","vino","wineglass"]',
    1, 214
  ),
  (
    'horn_tankard',
    'Horn Tankard',
    'horn tankards',
    'A drinking horn capped with brass. Holds rather a lot.',
    '/assets/items/horn_tankard.png',
    100,
    10,
    '["{sender} slides {target} {num} {item_name} across the table.","{sender} hands {target} {num} {item_name}. Skol."]',
    '["{sender} flings {num} {item_name} at {target}!","{sender} hurls {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. Sloshy."]',
    '["horn","drinking horn"]',
    1, 215
  ),
  (
    'a_boot',
    'A Boot',
    'boots',
    'Just a boot. Single, well-worn, slightly damp.',
    '/assets/items/a_boot.png',
    80,
    10,
    '["{sender} hands {target} {num} {item_name}. \"You''ll need this.\"","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} chucks {num} {item_name} at {target}. Classic."]',
    '["{sender} drops {num} {item_name} on {target}. *clunk*"]',
    '["boot","shoe"]',
    1, 250
  ),
  (
    'rotten_egg',
    'Rotten Egg',
    'rotten eggs',
    'An egg that has seen better weeks.',
    '/assets/items/rotten_egg.png',
    25,
    50,
    '["{sender} hands {target} {num} {item_name}. \"A gift.\"","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! The smell, the smell.","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. The smell will haunt the hallway."]',
    '["stink egg","egg"]',
    1, 251
  ),
  (
    'snowball',
    'Snowball',
    'snowballs',
    'A perfectly packed snowball. Cold to the touch.',
    '/assets/items/snowball.png',
    30,
    99,
    '["{sender} hands {target} {num} {item_name}. \"Don''t melt them.\"","{sender} offers {target} {num} {item_name}."]',
    '["{sender} pelts {target} with {num} {item_name}!","{sender} hurls {num} {item_name} at {target}. SNOW FIGHT!"]',
    '["{sender} drops {num} {item_name} down {target}''s collar."]',
    '["snow"]',
    1, 252
  ),
  (
    'water_balloon',
    'Water Balloon',
    'water balloons',
    'A balloon, taut with water. The summer classic.',
    '/assets/items/water_balloon.png',
    30,
    99,
    '["{sender} hands {target} {num} {item_name}. Gently, gently.","{sender} offers {target} {num} {item_name}."]',
    '["{sender} pelts {target} with {num} {item_name}! *POP*","{sender} hurls {num} {item_name} at {target}. Direct hit."]',
    '["{sender} drops {num} {item_name} on {target}. Splash zone."]',
    '["balloon","splash"]',
    1, 253
  ),
  (
    'rubber_ducky',
    'Rubber Ducky',
    'rubber duckies',
    'A small yellow rubber duck. Squeaks unsettlingly.',
    '/assets/items/rubber_ducky.png',
    60,
    20,
    '["{sender} hands {target} {num} {item_name}. *squeak*","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! *SQUEAK*","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. *squeak*"]',
    '["ducky","rubber duck","duck"]',
    1, 254
  ),
  (
    'frog',
    'Frog',
    'frogs',
    'A small green frog. Surprisingly cooperative.',
    '/assets/items/frog.png',
    80,
    10,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} flings {num} {item_name} at {target}. *RIBBIT*"]',
    '["{sender} drops {num} {item_name} on {target}. They hop indignantly away."]',
    '["toad"]',
    1, 255
  ),
  (
    'cursed_spud',
    'Cursed Spud',
    'cursed spuds',
    'A potato of distinctly malevolent provenance. Will not stop staring.',
    '/assets/items/cursed_spud.png',
    50,
    10,
    '["{sender} hands {target} {num} {item_name}. The curse is now {target}''s problem.","{sender} offers {target} {num} {item_name}. \"It''s just a potato.\""]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} flings {num} {item_name} at {target}. Bad omens trail behind."]',
    '["{sender} drops {num} {item_name} on {target}. {target} now has very strange dreams."]',
    '["cursed potato","potato"]',
    1, 256
  ),
  (
    'manure',
    'Manure',
    'piles of manure',
    'A pile of fertilizer. For your garden. Mostly.',
    '/assets/items/manure.png',
    30,
    20,
    '["{sender} hands {target} {num} {item_name}. \"For the roses.\"","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} flings {num} {item_name} at {target}. Unpleasantly."]',
    '["{sender} drops {num} {item_name} on {target}. The shower line is forming."]',
    '["dung","compost"]',
    1, 257
  ),
  (
    'candle',
    'Candle',
    'candles',
    'A wax candle. Flickers when stared at.',
    '/assets/items/candle.png',
    50,
    20,
    '["{sender} hands {target} {num} {item_name}.","{sender} lights and offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}. Wax flies.","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. Wax everywhere."]',
    '["tallow","wax"]',
    1, 300
  ),
  (
    'feather',
    'Feather',
    'feathers',
    'A long, soft feather. Probably from something large.',
    '/assets/items/feather.png',
    40,
    50,
    '["{sender} hands {target} {num} {item_name}.","{sender} tickles {target} with {num} {item_name}."]',
    '["{sender} tosses {num} {item_name} at {target}. They drift gently down.","{sender} flicks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. *fwoosh* — settle, settle."]',
    '["plume"]',
    1, 301
  ),
  (
    'compass',
    'Compass',
    'compasses',
    'A brass compass. Always points toward someone, never quite north.',
    '/assets/items/compass.png',
    250,
    5,
    '["{sender} hands {target} {num} {item_name}. \"Don''t lose your way.\"","{sender} entrusts {target} with {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. The needle spins."]',
    '["navigator","directions"]',
    1, 302
  ),
  (
    'hourglass',
    'Hourglass',
    'hourglasses',
    'A glass hourglass. Sand runs at suspicious speeds.',
    '/assets/items/hourglass.png',
    300,
    3,
    '["{sender} hands {target} {num} {item_name}. \"Your time starts now.\"","{sender} entrusts {target} with {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} chucks {num} {item_name} at {target}. Time, shattered."]',
    '["{sender} drops {num} {item_name} on {target}. Sand everywhere."]',
    '["timer","sandglass"]',
    1, 303
  ),
  (
    'lantern',
    'Lantern',
    'lanterns',
    'An oil lantern. Casts long shadows.',
    '/assets/items/lantern.png',
    200,
    5,
    '["{sender} hands {target} {num} {item_name}. \"Don''t drop it.\"","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} chucks {num} {item_name} at {target}. The lantern, regrettably, breaks."]',
    '["{sender} drops {num} {item_name} on {target}. Sets nothing on fire. Probably."]',
    '["light","lamp"]',
    1, 304
  ),
  (
    'old_key',
    'Old Key',
    'old keys',
    'An old iron key. Locks something, somewhere.',
    '/assets/items/old_key.png',
    150,
    10,
    '["{sender} hands {target} {num} {item_name}. \"This unlocks something. Probably.\"","{sender} entrusts {target} with {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. *clink*"]',
    '["key","skeleton key"]',
    1, 305
  ),
  (
    'quill_inkwell',
    'Quill & Inkwell',
    'quill-and-inkwell sets',
    'A feather quill and a corked inkwell. Ready to scribe.',
    '/assets/items/quill_inkwell.png',
    200,
    5,
    '["{sender} hands {target} {num} {item_name}. \"Write something good.\"","{sender} entrusts {target} with {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} flings {num} {item_name} at {target}. Ink, everywhere."]',
    '["{sender} drops {num} {item_name} on {target}. Ink splatter."]',
    '["quill","inkwell","pen","writing set"]',
    1, 306
  ),
  (
    'servant_bell',
    'Servant Bell',
    'servant bells',
    'A small brass bell. Summons help, eventually.',
    '/assets/items/servant_bell.png',
    250,
    5,
    '["{sender} hands {target} {num} {item_name}. \"Ring when you need me.\"","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! *DING*","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. The ring echoes."]',
    '["bell","summon"]',
    1, 307
  ),
  (
    'smoking_pipe',
    'Smoking Pipe',
    'smoking pipes',
    'A carved wooden pipe. Smoke optional.',
    '/assets/items/smoking_pipe.png',
    200,
    5,
    '["{sender} hands {target} {num} {item_name}.","{sender} offers {target} {num} {item_name}. \"Take a draw.\""]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. Ash everywhere."]',
    '["pipe","tobacco pipe"]',
    1, 308
  ),
  (
    'treasure_map',
    'Treasure Map',
    'treasure maps',
    'A parchment map. X marks something. Probably.',
    '/assets/items/treasure_map.png',
    500,
    10,
    '["{sender} unfurls and hands {target} {num} {item_name}. \"Good luck.\"","{sender} entrusts {target} with {num} {item_name}."]',
    '["{sender} flings {num} {item_name} at {target}!","{sender} hurls {num} {item_name} at {target}. Most undignified."]',
    '["{sender} drops {num} {item_name} on {target}. The map slowly unrolls itself."]',
    '["map","treasure chart"]',
    1, 309
  ),
  (
    'bouquet',
    'Bouquet',
    'bouquets',
    'A handpicked bouquet of seasonal flowers. Slightly damp.',
    '/assets/items/bouquet.png',
    250,
    5,
    '["{sender} hands {target} {num} {item_name}. *swoon*","{sender} presents {target} with {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}. Petals fly.","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. Petals, petals, petals."]',
    '["bunch of flowers"]',
    1, 350
  ),
  (
    'love_letter',
    'Love Letter',
    'love letters',
    'A folded letter, scented with rose. Read it later.',
    '/assets/items/love_letter.png',
    100,
    10,
    '["{sender} shyly hands {target} {num} {item_name}.","{sender} slips {num} {item_name} to {target}."]',
    '["{sender} folds and hurls {num} {item_name} at {target}. Origami delivery.","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} lets {num} {item_name} fall at {target}''s feet."]',
    '["love note","billet doux"]',
    1, 351
  ),
  (
    'enagement_ring',
    'Engagement Ring',
    'engagement rings',
    'A jeweled ring. The kind that asks a Question.',
    '/assets/items/enagement_ring.png',
    5000,
    2,
    '["{sender} kneels and offers {target} {num} {item_name}. \"Will you?\"","{sender} presents {target} with {num} {item_name}. The Question hangs."]',
    '["{sender} hurls {num} {item_name} at {target}. Rejection — dramatic.","{sender} chucks {num} {item_name} at {target}. *clink* — heart-shaped impact."]',
    '["{sender} drops {num} {item_name} on {target}''s lap. Awkward proposal."]',
    '["ring","proposal"]',
    1, 352
  ),
  (
    'keepsake_locket',
    'Keepsake Locket',
    'keepsake lockets',
    'A silver locket on a fine chain. Contains a memory.',
    '/assets/items/keepsake_locket.png',
    800,
    5,
    '["{sender} clasps {num} {item_name} around {target}''s neck.","{sender} offers {target} {num} {item_name}. \"Keep me close.\""]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} flings {num} {item_name} at {target}. The chain whips."]',
    '["{sender} drops {num} {item_name} on {target}. *clink*"]',
    '["locket","memento"]',
    1, 353
  ),
  (
    'masquerade_mask',
    'Masquerade Mask',
    'masquerade masks',
    'A delicate mask of gold leaf and ribbon. For evenings of mystery.',
    '/assets/items/masquerade_mask.png',
    500,
    5,
    '["{sender} ties {num} {item_name} onto {target}.","{sender} offers {target} {num} {item_name}. \"Wear it well.\""]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} flings {num} {item_name} at {target}. Ribbons trail."]',
    '["{sender} drops {num} {item_name} on {target}''s face. Identity, swapped."]',
    '["mask","disguise"]',
    1, 354
  ),
  (
    'paerlescent_shell',
    'Pearlescent Shell',
    'pearlescent shells',
    'A whorled shell that shimmers in every color of the tide.',
    '/assets/items/paerlescent_shell.png',
    600,
    5,
    '["{sender} hands {target} {num} {item_name}.","{sender} offers {target} {num} {item_name}. Listen for the sea."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} flings {num} {item_name} at {target}. Iridescent arc."]',
    '["{sender} drops {num} {item_name} on {target}. The ocean whispers."]',
    '["shell","pearl shell","seashell"]',
    1, 355
  ),
  (
    'kaal_dragon_plushie',
    'Kaal Dragon Plushie',
    'Kaal dragon plushies',
    'A handcrafted plushie of Kaal, the realm''s most squeezable dragon.',
    '/assets/items/kaal_dragon_plushie.png',
    1500,
    3,
    '["{sender} hands {target} {num} {item_name}. Limited edition!","{sender} offers {target} {num} {item_name}. *roars adorably*"]',
    '["{sender} hurls {num} {item_name} at {target}! *roar* (muffled)","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. Heroically squishy."]',
    '["plushie","dragon plush","kaal plush","kaal"]',
    1, 356
  ),
  (
    'magical_rune',
    'Magical Rune',
    'magical runes',
    'A stone tablet inscribed with a glowing rune. Hums faintly.',
    '/assets/items/magical_rune.png',
    500,
    10,
    '["{sender} hands {target} {num} {item_name}.","{sender} carefully presents {target} with {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! The air sparks.","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. Magic discharges."]',
    '["rune","glyph"]',
    1, 380
  ),
  (
    'mysterious_potion',
    'Mysterious Potion',
    'mysterious potions',
    'A vial of liquid that shifts color when you look away.',
    '/assets/items/mysterious_potion.png',
    400,
    10,
    '["{sender} hands {target} {num} {item_name}. \"Probably safe.\"","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! *SHATTER*","{sender} flings {num} {item_name} at {target}. The fumes."]',
    '["{sender} drops {num} {item_name} on {target}. Color-changing splash."]',
    '["potion","elixir","vial"]',
    1, 381
  ),
  (
    'magical_book',
    'Magical Book',
    'magical books',
    'A heavy leather tome. The pages turn themselves when no one is looking.',
    '/assets/items/magical_book.png',
    1200,
    3,
    '["{sender} hands {target} {num} {item_name}. \"Read carefully.\"","{sender} entrusts {target} with {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! Heavy.","{sender} flings {num} {item_name} at {target}. Pages flutter."]',
    '["{sender} drops {num} {item_name} on {target}. *THUD*"]',
    '["tome","grimoire","spellbook"]',
    1, 382
  ),
  (
    'magic_sphere',
    'Magic Sphere',
    'magic spheres',
    'A crystal sphere. Shows possibilities the viewer doesn''t quite want.',
    '/assets/items/magic_sphere.png',
    1500,
    3,
    '["{sender} hands {target} {num} {item_name}. \"Look inside.\"","{sender} carefully offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! Heavy, swirling, ominous.","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. Reality, briefly, ripples."]',
    '["crystal ball","orb"]',
    1, 383
  ),
  (
    'playing_cards',
    'Playing Cards',
    'decks of playing cards',
    'A deck of cards. Suits unfamiliar. Always one card short.',
    '/assets/items/playing_cards.png',
    100,
    10,
    '["{sender} deals {target} {num} {item_name}.","{sender} hands {target} {num} {item_name}. \"Cut for deal.\""]',
    '["{sender} flings {num} {item_name} at {target}! Cards everywhere.","{sender} hurls {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. 52-card pickup."]',
    '["cards","deck"]',
    1, 420
  ),
  (
    'playing_dice',
    'Playing Dice',
    'sets of playing dice',
    'A set of polyhedral dice. They roll a little too well.',
    '/assets/items/playing_dice.png',
    100,
    10,
    '["{sender} hands {target} {num} {item_name}. \"Roll well.\"","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! Natural 20.","{sender} pelts {target} with {num} {item_name}."]',
    '["{sender} drops {num} {item_name} on {target}. Each one lands on 1."]',
    '["dice","d20"]',
    1, 421
  ),
  (
    'treasure_chest',
    'Treasure Chest',
    'treasure chests',
    'A small ironbound chest. Locked, of course. Contents unverified.',
    '/assets/items/treasure_chest.png',
    5000,
    2,
    '["{sender} hands {target} the key to {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}."]',
    '["{sender} heaves {num} {item_name} at {target}! Treasure flies.","{sender} hurls {num} {item_name} at {target}. *CRASH*"]',
    '["{sender} drops {num} {item_name} on {target}. The lid pops open mid-fall."]',
    '["chest","loot box"]',
    1, 422
  ),
  (
    'copper_ingot',
    'Copper Ingot',
    'copper ingots',
    'A bar of refined copper. Heavier than expected.',
    '/assets/items/copper_ingot.png',
    200,
    20,
    '["{sender} hands {target} {num} {item_name}.","{sender} offers {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. *clang*"]',
    '["copper","copper bar"]',
    1, 450
  ),
  (
    'silver_ingot',
    'Silver Ingot',
    'silver ingots',
    'A bar of pure silver. Reflective. Cool to the touch.',
    '/assets/items/silver_ingot.png',
    1000,
    10,
    '["{sender} hands {target} {num} {item_name}.","{sender} presents {target} with {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. *thunk*"]',
    '["silver","silver bar"]',
    1, 451
  ),
  (
    'gold_ingot',
    'Gold Ingot',
    'gold ingots',
    'A bar of solid gold. A small fortune in a hand-sized brick.',
    '/assets/items/gold_ingot.png',
    5000,
    5,
    '["{sender} hands {target} {num} {item_name}.","{sender} presents {target} with {num} {item_name}. Heavy gift."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} chucks {num} {item_name} at {target}. Ouch."]',
    '["{sender} drops {num} {item_name} on {target}. *THUD* The wealthy way to be flattened."]',
    '["gold bar","bullion"]',
    1, 452
  ),
  (
    'leather_armor',
    'Leather Armor',
    'sets of leather armor',
    'A suit of tooled leather. Light, supple, slightly squeaky.',
    '/assets/items/leather_armor.png',
    1500,
    3,
    '["{sender} hands {target} {num} {item_name}.","{sender} presents {target} with {num} {item_name}. \"Suit up.\""]',
    '["{sender} hurls {num} {item_name} at {target}! Floppy impact.","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. *fwump*"]',
    '["leather"]',
    1, 500
  ),
  (
    'chainmail_armor',
    'Chainmail Armor',
    'sets of chainmail armor',
    'Hundreds of riveted rings. Surprisingly comfortable. Heavy when wet.',
    '/assets/items/chainmail_armor.png',
    2500,
    2,
    '["{sender} hands {target} {num} {item_name}.","{sender} presents {target} with {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! *jingle jingle CRASH*","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. They are now wearing it."]',
    '["chainmail","mail"]',
    1, 501
  ),
  (
    'plate_armor',
    'Plate Armor',
    'sets of plate armor',
    'Hammered steel plates fitted to the body. Knightly.',
    '/assets/items/plate_armor.png',
    4000,
    2,
    '["{sender} hands {target} {num} {item_name}.","{sender} presents {target} with {num} {item_name}. \"For the joust.\""]',
    '["{sender} hurls {num} {item_name} at {target}! *CLANG*","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. The breastplate alone could flatten a horse."]',
    '["plate","full plate"]',
    1, 502
  ),
  (
    'mage_robes',
    'Mage Robes',
    'sets of mage robes',
    'Robes of deep blue silk, embroidered with constellations.',
    '/assets/items/mage_robes.png',
    3000,
    2,
    '["{sender} hands {target} {num} {item_name}.","{sender} presents {target} with {num} {item_name}. Mystical aura, included."]',
    '["{sender} hurls {num} {item_name} at {target}! Robes billow.","{sender} flings {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. Tangled in stars."]',
    '["robes","wizard robes"]',
    1, 503
  ),
  (
    'golden_armor',
    'Golden Armor',
    'sets of golden armor',
    'Gilded plate, impractical and spectacular.',
    '/assets/items/golden_armor.png',
    6000,
    1,
    '["{sender} hands {target} {num} {item_name}.","{sender} presents {target} with {num} {item_name}. Royal regalia."]',
    '["{sender} hurls {num} {item_name} at {target}! Glittering, devastating.","{sender} chucks {num} {item_name} at {target}."]',
    '["{sender} drops {num} {item_name} on {target}. They are momentarily royalty, then crushed."]',
    '["gold armor","gilt armor"]',
    1, 504
  ),
  (
    'royal_steel_armor',
    'Royal Steel Armor',
    'sets of royal steel armor',
    'Master-forged steel etched with the royal sigil. Heirloom-grade.',
    '/assets/items/royal_steel_armor.png',
    8000,
    1,
    '["{sender} hands {target} {num} {item_name}.","{sender} presents {target} with {num} {item_name}. Knighthood, optional."]',
    '["{sender} hurls {num} {item_name} at {target}!","{sender} chucks {num} {item_name} at {target}. Crown jewel impact."]',
    '["{sender} drops {num} {item_name} on {target}. Knighted by accident."]',
    '["royal armor","steel armor"]',
    1, 505
  ),
  (
    'chromtic_legendary_armor',
    'Chromatic Legendary Armor',
    'sets of chromatic legendary armor',
    'Armor of shifting iridescent metal. Said to fit every wearer differently.',
    '/assets/items/chromtic_legendary_armor.png',
    15000,
    1,
    '["{sender} bestows upon {target} {num} {item_name}. The realm holds its breath.","{sender} presents {target} with {num} {item_name}. A legend in their grasp."]',
    '["{sender} hurls {num} {item_name} at {target}! Colors of impact: all of them.","{sender} chucks {num} {item_name} at {target}. Reality shifts to match."]',
    '["{sender} drops {num} {item_name} on {target}. They are now legendary AND flattened."]',
    '["chromatic","legendary armor","chromatic armor"]',
    1, 506
  );
