-- 44 new builtin items from the latest icon drop: 42 pets in
-- the new `pet` category, and 2 joke-tier items (banana_hammock,
-- glorious_panties). Pets use generic give templates (admin can
-- tweak per-row via the editor); throw/drop arrays are empty so
-- those commands are disabled on pets — you don't throw pets.
-- Stack limit 1 per pet: each pet is a unique companion, not
-- a stackable consumable. Pins live in identity_pet_collection
-- (migration 0105), separate from the 10-slot item collection.
--
-- Order slots (700+) leave a wide gap below the existing 100s-
-- 500s ranges so new ad-hoc admin items can squeeze in between
-- without re-numbering. Pricing escalates: common animals 500-
-- 2000, horses 1000-3500, premium/mythical 2000-15000, dragons
-- 15000-35000.

INSERT INTO `items` (`key`, `name`, `name_plural`, `description`, `icon_url`, `price`, `stack_limit`, `give_messages_json`, `throw_messages_json`, `drop_messages_json`, `aliases_json`, `category`, `is_builtin`, `order`) VALUES
  (
    'toad',
    'Toad',
    'toads',
    'A speckled toad. Surprisingly affectionate.',
    '/assets/items/toad.png',
    500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["puddle hopper"]',
    'pet', 1, 700
  ),
  (
    'fox',
    'Fox',
    'foxes',
    'A red fox. Cunning expression, fluffy tail.',
    '/assets/items/fox.png',
    1000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["red fox"]',
    'pet', 1, 701
  ),
  (
    'wolf',
    'Wolf',
    'wolves',
    'A grey wolf. Loyal once you''ve earned it.',
    '/assets/items/wolf.png',
    1200,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["grey wolf"]',
    'pet', 1, 702
  ),
  (
    'white_wolf',
    'White Wolf',
    'white wolves',
    'A snow-white wolf. Eyes like ice.',
    '/assets/items/white_wolf.png',
    1500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["snow wolf"]',
    'pet', 1, 703
  ),
  (
    'black_wolf',
    'Black Wolf',
    'black wolves',
    'A jet-black wolf. Quiet, watchful.',
    '/assets/items/black_wolf.png',
    1500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["dark wolf"]',
    'pet', 1, 704
  ),
  (
    'bat',
    'Bat',
    'bats',
    'A small bat. Sleeps upside down, judges your decor.',
    '/assets/items/bat.png',
    600,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["fruit bat"]',
    'pet', 1, 705
  ),
  (
    'owl',
    'Owl',
    'owls',
    'A wise-eyed owl. Suspiciously well-informed.',
    '/assets/items/owl.png',
    800,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '[]',
    'pet', 1, 706
  ),
  (
    'snowy_owl',
    'Snowy Owl',
    'snowy owls',
    'A snow-white owl. Silent flight.',
    '/assets/items/snowy_owl.png',
    1000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["white owl"]',
    'pet', 1, 707
  ),
  (
    'raven',
    'Raven',
    'ravens',
    'A glossy raven. Remembers faces.',
    '/assets/items/raven.png',
    800,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["crow"]',
    'pet', 1, 708
  ),
  (
    'tiger',
    'Tiger',
    'tigers',
    'A young tiger. Big enough to be a problem.',
    '/assets/items/tiger.png',
    2000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '[]',
    'pet', 1, 709
  ),
  (
    'red_panda',
    'Red Panda',
    'red pandas',
    'A red panda. Mostly tail and indignation.',
    '/assets/items/red_panda.png',
    1500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["panda"]',
    'pet', 1, 710
  ),
  (
    'cottontail_bunny',
    'Cottontail Bunny',
    'cottontail bunnies',
    'A small cottontail bunny. Hops with purpose.',
    '/assets/items/cottontail_bunny.png',
    500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["cottontail"]',
    'pet', 1, 711
  ),
  (
    'white_bunny',
    'White Bunny',
    'white bunnies',
    'A pure-white bunny. Twitchy nose.',
    '/assets/items/white_bunny.png',
    500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '[]',
    'pet', 1, 712
  ),
  (
    'moon_bunny',
    'Moon Bunny',
    'moon bunnies',
    'A lunar-grey bunny said to nibble starlight.',
    '/assets/items/moon_bunny.png',
    1500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["lunar bunny"]',
    'pet', 1, 713
  ),
  (
    'brown_horse',
    'Brown Horse',
    'brown horses',
    'A solid brown horse. Reliable.',
    '/assets/items/brown_horse.png',
    1000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["bay horse"]',
    'pet', 1, 714
  ),
  (
    'buckskin_horse',
    'Buckskin Horse',
    'buckskin horses',
    'A tan horse with a black mane. Sturdy.',
    '/assets/items/buckskin_horse.png',
    1200,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["buckskin"]',
    'pet', 1, 715
  ),
  (
    'appaloosa_horse',
    'Appaloosa Horse',
    'appaloosa horses',
    'A spotted Appaloosa. Hardy and surefooted.',
    '/assets/items/appaloosa_horse.png',
    1500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["appaloosa"]',
    'pet', 1, 716
  ),
  (
    'dapple_gray_horse',
    'Dapple-Gray Horse',
    'dapple-gray horses',
    'A dappled grey. Looks like marbled stone.',
    '/assets/items/dapple_gray_horse.png',
    1800,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["dapple grey","dapple"]',
    'pet', 1, 717
  ),
  (
    'draft_horse',
    'Draft Horse',
    'draft horses',
    'A heavy-set workhorse. Doesn''t startle.',
    '/assets/items/draft_horse.png',
    1800,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["workhorse"]',
    'pet', 1, 718
  ),
  (
    'mustang_horse',
    'Mustang Horse',
    'mustang horses',
    'A half-wild mustang. Independent streak.',
    '/assets/items/mustang_horse.png',
    1500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["mustang"]',
    'pet', 1, 719
  ),
  (
    'arabian_horse',
    'Arabian Horse',
    'arabian horses',
    'A fine-boned arabian. Hot-blooded.',
    '/assets/items/arabian_horse.png',
    2200,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["arabian"]',
    'pet', 1, 720
  ),
  (
    'camarillo_horse',
    'Camarillo Horse',
    'camarillo horses',
    'A rare white camarillo. Storybook coat.',
    '/assets/items/camarillo_horse.png',
    2400,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["camarillo"]',
    'pet', 1, 721
  ),
  (
    'haflinger_horse',
    'Haflinger Horse',
    'haflinger horses',
    'A golden haflinger. Cheerful disposition.',
    '/assets/items/haflinger_horse.png',
    2500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["haflinger"]',
    'pet', 1, 722
  ),
  (
    'norwegian_fjord_horse',
    'Norwegian Fjord Horse',
    'norwegian fjord horses',
    'A compact Norwegian fjord. Mohawk mane.',
    '/assets/items/norwegian_fjord_horse.png',
    2500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["fjord horse","fjord"]',
    'pet', 1, 723
  ),
  (
    'shire_draft_horse',
    'Shire Draft Horse',
    'shire draft horses',
    'A towering shire draft. Hooves like dinner plates.',
    '/assets/items/shire_draft_horse.png',
    3000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["shire","shire horse"]',
    'pet', 1, 724
  ),
  (
    'akhal_teke_horse',
    'Akhal-Teke Horse',
    'Akhal-Teke horses',
    'A metallic-sheened Akhal-Teke. The golden ghost.',
    '/assets/items/Akhal-Teke_horse.png',
    3500,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["akhal-teke","akhalteke","teke"]',
    'pet', 1, 725
  ),
  (
    'pegasus_horse',
    'Pegasus',
    'pegasi',
    'A winged horse. Flight is part of the package.',
    '/assets/items/pegasus_horse.png',
    8000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["pegasus","winged horse"]',
    'pet', 1, 726
  ),
  (
    'unicorn_horse',
    'Unicorn',
    'unicorns',
    'A horned unicorn. Pure-white, single horn, opinionated.',
    '/assets/items/unicorn_horse.png',
    10000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["unicorn"]',
    'pet', 1, 727
  ),
  (
    'pestilence_horse',
    'Pestilence Horse',
    'pestilence horses',
    'A pale horse with a fevered gaze. Riders welcome.',
    '/assets/items/pestilence_horse.png',
    15000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["pale horse","pestilence"]',
    'pet', 1, 728
  ),
  (
    'slime_pet',
    'Slime',
    'slimes',
    'A blue gelatinous slime. Cheerful, jiggly, slightly damp.',
    '/assets/items/slime_pet.png',
    2000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["slime"]',
    'pet', 1, 729
  ),
  (
    'carbunclo_pet',
    'Carbuncle',
    'carbuncles',
    'A small creature with a single ruby on its forehead.',
    '/assets/items/carbunclo_pet.png',
    3000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["carbuncle"]',
    'pet', 1, 730
  ),
  (
    'mimic_chest_pet',
    'Mimic Chest',
    'mimic chests',
    'A treasure chest with teeth. Surprisingly loyal once tamed.',
    '/assets/items/mimic_chest_pet.png',
    5000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["mimic"]',
    'pet', 1, 731
  ),
  (
    'gryphon_baby',
    'Baby Gryphon',
    'baby gryphons',
    'A fledgling gryphon. Half eagle, half lion, fully chaotic.',
    '/assets/items/gryphon_baby.png',
    8000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["gryphon","griffon"]',
    'pet', 1, 732
  ),
  (
    'spirit_stag',
    'Spirit Stag',
    'spirit stags',
    'A translucent stag wreathed in soft light.',
    '/assets/items/spirit_stag.png',
    10000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["ghost stag","spirit deer"]',
    'pet', 1, 733
  ),
  (
    'kirin_stag',
    'Kirin',
    'kirin',
    'A celestial kirin. Walks without disturbing grass.',
    '/assets/items/kirin_stag.png',
    12000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["qilin"]',
    'pet', 1, 734
  ),
  (
    'phoenix_chick',
    'Phoenix Chick',
    'phoenix chicks',
    'A fledgling phoenix. Already trailing embers.',
    '/assets/items/phoenix_chick.png',
    15000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["phoenix"]',
    'pet', 1, 735
  ),
  (
    'celestial_fox',
    'Celestial Fox',
    'celestial foxes',
    'A starry-pelted fox. Said to guide lost travelers.',
    '/assets/items/celestial_fox.png',
    10000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["star fox"]',
    'pet', 1, 736
  ),
  (
    'kitsune',
    'Kitsune',
    'kitsune',
    'A nine-tailed kitsune. Trickster. Wise. Maybe untrustworthy.',
    '/assets/items/kitsune.png',
    15000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["nine-tail","ninetail fox"]',
    'pet', 1, 737
  ),
  (
    'forest_dragon',
    'Forest Dragon',
    'forest dragons',
    'A scaled dragon the color of moss and bark.',
    '/assets/items/forest_dragon.png',
    18000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["green dragon","wood dragon"]',
    'pet', 1, 738
  ),
  (
    'crystal_dragon',
    'Crystal Dragon',
    'crystal dragons',
    'A crystalline dragon. Refracts light in unsettling ways.',
    '/assets/items/crystal_dragon.png',
    20000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["crystal drake"]',
    'pet', 1, 739
  ),
  (
    'ice_dragon',
    'Ice Dragon',
    'ice dragons',
    'An ice-pale dragon. Breath like a winter morning.',
    '/assets/items/ice_dragon.png',
    25000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["frost dragon"]',
    'pet', 1, 740
  ),
  (
    'lightning_dragon',
    'Lightning Dragon',
    'lightning dragons',
    'A storm-blue dragon. Scales hum.',
    '/assets/items/lightning_dragon.png',
    25000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["storm dragon"]',
    'pet', 1, 741
  ),
  (
    'red_dragon',
    'Red Dragon',
    'red dragons',
    'A fire-red dragon. Smoke trails when it sleeps.',
    '/assets/items/red_dragon.png',
    30000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["fire dragon"]',
    'pet', 1, 742
  ),
  (
    'shadow_dragon',
    'Shadow Dragon',
    'shadow dragons',
    'A void-black dragon. Hard to look at directly.',
    '/assets/items/shadow_dragon.png',
    35000,
    1,
    '["{sender} hands {target} {num} {item_name}. \"Take care of them.\"","{sender} gifts {target} {num} {item_name}.","{sender} entrusts {target} with {num} {item_name}. They look up at {target} expectantly."]',
    '[]',
    '[]',
    '["void dragon","dark dragon"]',
    'pet', 1, 743
  ),
  (
    'banana_hammock',
    'Banana Hammock',
    'banana hammocks',
    'A sling-style swimsuit. Sized for confidence.',
    '/assets/items/banana_hammock.png',
    200,
    5,
    '["{sender} hands {target} {num} {item_name}. Eye contact, sustained.","{sender} gifts {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! Direct hit.","{sender} pelts {target} with {num} {item_name}."]',
    '["{sender} drops {num} {item_name} on {target}. The horror.","{sender} flings {num} {item_name} onto {target}. Wears it well."]',
    '["sling","mankini"]',
    'joke', 1, 800
  ),
  (
    'glorious_panties',
    'Glorious Panties',
    'pairs of glorious panties',
    'A pair of decidedly ceremonial undergarments. Frilly and proud.',
    '/assets/items/glorious_panties.png',
    200,
    5,
    '["{sender} hands {target} {num} {item_name}. Eye contact, sustained.","{sender} gifts {target} {num} {item_name}."]',
    '["{sender} hurls {num} {item_name} at {target}! Direct hit.","{sender} pelts {target} with {num} {item_name}."]',
    '["{sender} drops {num} {item_name} on {target}. The horror.","{sender} flings {num} {item_name} onto {target}. Wears it well."]',
    '["panties","frilly underwear","drawers"]',
    'joke', 1, 801
  );
