-- 0125_descent_banner_url.sql
-- Reserved no-op. Adventure-game feature was removed before merge; slot kept
-- to prevent migration number reuse. apply-migrations.mjs records it as applied
-- with zero statements run.
