-- 0126_game_session_slots.sql
-- Reserved no-op. Adventure-game feature was removed before merge; slot kept
-- to prevent migration number reuse. apply-migrations.mjs records it as applied
-- with zero statements run.
