-- Repair message_reactions rows where unicode_char accidentally
-- stored the catalog NAME instead of the codepoint. The route +
-- the reactions loader both normalize lazily now, but this
-- migration physically rewrites the column so the unique index
-- (which keys on the literal value) dedupes correctly going forward.
--
-- Generated from packages/shared/src/unicodeEmoji.ts (627 entries).
-- Re-run apps/server/scripts/gen-reaction-cleanup-sql.mjs if the
-- catalog changes and an older curated mapping needs the same
-- treatment.
--
-- Strategy:
--   1. UPDATE OR IGNORE rewrites every row whose unicode_char is a
--      known catalog name. The OR IGNORE skips rows that would
--      collide with an already-correct row on the unique index —
--      same (target, user, target_id) with both the broken and the
--      fixed value sitting in the table.
--   2. A trailing DELETE removes the still-broken stragglers so the
--      table only carries codepoint-shaped values from here on.

WITH name_to_char(name, char) AS (VALUES
  ('grinning', '😀'),
  ('smiley', '😃'),
  ('smile', '😄'),
  ('grin', '😁'),
  ('laughing', '😆'),
  ('sweat smile', '😅'),
  ('rofl', '🤣'),
  ('joy', '😂'),
  ('slight smile', '🙂'),
  ('upside down', '🙃'),
  ('wink', '😉'),
  ('blush', '😊'),
  ('innocent', '😇'),
  ('smiling hearts', '🥰'),
  ('heart eyes', '😍'),
  ('star struck', '🤩'),
  ('blowing kiss', '😘'),
  ('kissing', '😗'),
  ('kissing closed eyes', '😚'),
  ('kissing smile', '😙'),
  ('smiling tear', '🥲'),
  ('yum', '😋'),
  ('tongue', '😛'),
  ('winking tongue', '😜'),
  ('zany', '🤪'),
  ('squint tongue', '😝'),
  ('money mouth', '🤑'),
  ('hug', '🤗'),
  ('hand over mouth', '🤭'),
  ('shushing', '🤫'),
  ('thinking', '🤔'),
  ('zipper mouth', '🤐'),
  ('raised brow', '🤨'),
  ('neutral', '😐'),
  ('expressionless', '😑'),
  ('no mouth', '😶'),
  ('smirk', '😏'),
  ('unamused', '😒'),
  ('eye roll', '🙄'),
  ('grimace', '😬'),
  ('lying', '🤥'),
  ('relieved', '😌'),
  ('pensive', '😔'),
  ('sleepy', '😪'),
  ('drooling', '🤤'),
  ('sleeping', '😴'),
  ('mask', '😷'),
  ('fever', '🤒'),
  ('head bandage', '🤕'),
  ('nauseated', '🤢'),
  ('vomit', '🤮'),
  ('sneeze', '🤧'),
  ('hot', '🥵'),
  ('cold', '🥶'),
  ('woozy', '🥴'),
  ('dizzy', '😵'),
  ('mind blown', '🤯'),
  ('cowboy', '🤠'),
  ('party', '🥳'),
  ('disguise', '🥸'),
  ('sunglasses', '😎'),
  ('nerd', '🤓'),
  ('monocle', '🧐'),
  ('confused', '😕'),
  ('worried', '😟'),
  ('slight frown', '🙁'),
  ('frown', '☹️'),
  ('open mouth', '😮'),
  ('hushed', '😯'),
  ('astonished', '😲'),
  ('flushed', '😳'),
  ('pleading', '🥺'),
  ('frowning open', '😦'),
  ('anguished', '😧'),
  ('fearful', '😨'),
  ('anxious sweat', '😰'),
  ('sad sweat', '😥'),
  ('cry', '😢'),
  ('loudly crying', '😭'),
  ('scream', '😱'),
  ('confounded', '😖'),
  ('persevere', '😣'),
  ('disappointed', '😞'),
  ('downcast sweat', '😓'),
  ('weary', '😩'),
  ('tired', '😫'),
  ('yawn', '🥱'),
  ('triumph', '😤'),
  ('rage', '😡'),
  ('angry', '😠'),
  ('swearing', '🤬'),
  ('imp', '😈'),
  ('angry imp', '👿'),
  ('skull', '💀'),
  ('poop', '💩'),
  ('clown', '🤡'),
  ('ogre', '👹'),
  ('goblin', '👺'),
  ('ghost', '👻'),
  ('alien', '👽'),
  ('space invader', '👾'),
  ('robot', '🤖'),
  ('100', '💯'),
  ('anger', '💢'),
  ('boom', '💥'),
  ('dizzy stars', '💫'),
  ('sweat drops', '💦'),
  ('dash', '💨'),
  ('hole', '🕳️'),
  ('bomb', '💣'),
  ('speech bubble', '💬'),
  ('thought bubble', '💭'),
  ('zzz', '💤'),
  ('wave', '👋'),
  ('raised back of hand', '🤚'),
  ('splayed hand', '🖐️'),
  ('raised hand', '✋'),
  ('vulcan', '🖖'),
  ('ok hand', '👌'),
  ('pinched fingers', '🤌'),
  ('pinching', '🤏'),
  ('victory', '✌️'),
  ('fingers crossed', '🤞'),
  ('love you', '🤟'),
  ('rock on', '🤘'),
  ('call me', '🤙'),
  ('left point', '👈'),
  ('right point', '👉'),
  ('up point', '👆'),
  ('middle finger', '🖕'),
  ('down point', '👇'),
  ('index up', '☝️'),
  ('thumbs up', '👍'),
  ('thumbs down', '👎'),
  ('fist', '✊'),
  ('punch', '👊'),
  ('left fist', '🤛'),
  ('right fist', '🤜'),
  ('clap', '👏'),
  ('raised hands', '🙌'),
  ('open hands', '👐'),
  ('palms up', '🤲'),
  ('handshake', '🤝'),
  ('pray', '🙏'),
  ('nail polish', '💅'),
  ('selfie', '🤳'),
  ('flex', '💪'),
  ('robotic arm', '🦾'),
  ('eyes', '👀'),
  ('eye', '👁️'),
  ('tongue', '👅'),
  ('lips', '👄'),
  ('brain', '🧠'),
  ('anatomical heart', '🫀'),
  ('bone', '🦴'),
  ('baby', '👶'),
  ('child', '🧒'),
  ('boy', '👦'),
  ('girl', '👧'),
  ('person', '🧑'),
  ('man', '👨'),
  ('woman', '👩'),
  ('older person', '🧓'),
  ('old man', '👴'),
  ('old woman', '👵'),
  ('bowing', '🙇'),
  ('facepalm', '🤦'),
  ('shrug', '🤷'),
  ('dancing', '💃'),
  ('man dancing', '🕺'),
  ('walking', '🚶'),
  ('running', '🏃'),
  ('dog', '🐶'),
  ('cat', '🐱'),
  ('mouse', '🐭'),
  ('hamster', '🐹'),
  ('rabbit', '🐰'),
  ('fox', '🦊'),
  ('bear', '🐻'),
  ('panda', '🐼'),
  ('koala', '🐨'),
  ('tiger', '🐯'),
  ('lion', '🦁'),
  ('cow', '🐮'),
  ('pig', '🐷'),
  ('frog', '🐸'),
  ('monkey face', '🐵'),
  ('see no evil', '🙈'),
  ('hear no evil', '🙉'),
  ('speak no evil', '🙊'),
  ('monkey', '🐒'),
  ('chicken', '🐔'),
  ('penguin', '🐧'),
  ('bird', '🐦'),
  ('chick', '🐤'),
  ('duck', '🦆'),
  ('eagle', '🦅'),
  ('owl', '🦉'),
  ('bat', '🦇'),
  ('wolf', '🐺'),
  ('boar', '🐗'),
  ('horse face', '🐴'),
  ('unicorn', '🦄'),
  ('bee', '🐝'),
  ('bug', '🐛'),
  ('butterfly', '🦋'),
  ('snail', '🐌'),
  ('ladybug', '🐞'),
  ('turtle', '🐢'),
  ('snake', '🐍'),
  ('lizard', '🦎'),
  ('octopus', '🐙'),
  ('squid', '🦑'),
  ('shrimp', '🦐'),
  ('lobster', '🦞'),
  ('crab', '🦀'),
  ('fish', '🐟'),
  ('dolphin', '🐬'),
  ('whale', '🐳'),
  ('shark', '🦈'),
  ('crocodile', '🐊'),
  ('tiger body', '🐅'),
  ('leopard', '🐆'),
  ('zebra', '🦓'),
  ('gorilla', '🦍'),
  ('elephant', '🐘'),
  ('rhino', '🦏'),
  ('hippo', '🦛'),
  ('camel', '🐪'),
  ('two hump camel', '🐫'),
  ('giraffe', '🦒'),
  ('kangaroo', '🦘'),
  ('horse', '🐎'),
  ('pig body', '🐖'),
  ('ox', '🐂'),
  ('sheep', '🐑'),
  ('goat', '🐐'),
  ('deer', '🦌'),
  ('dog body', '🐕'),
  ('poodle', '🐩'),
  ('guide dog', '🦮'),
  ('cat body', '🐈'),
  ('rooster', '🐓'),
  ('turkey', '🦃'),
  ('peacock', '🦚'),
  ('parrot', '🦜'),
  ('tree', '🌳'),
  ('evergreen', '🌲'),
  ('palm tree', '🌴'),
  ('cactus', '🌵'),
  ('tulip', '🌷'),
  ('rose', '🌹'),
  ('wilted rose', '🥀'),
  ('hibiscus', '🌺'),
  ('cherry blossom', '🌸'),
  ('blossom', '🌼'),
  ('sunflower', '🌻'),
  ('sun', '☀️'),
  ('full moon face', '🌝'),
  ('new moon face', '🌚'),
  ('crescent moon', '🌙'),
  ('star', '⭐'),
  ('glowing star', '🌟'),
  ('sparkles', '✨'),
  ('lightning', '⚡'),
  ('fire', '🔥'),
  ('rainbow', '🌈'),
  ('cloud', '☁️'),
  ('snowflake', '❄️'),
  ('umbrella rain', '☔'),
  ('wave water', '🌊'),
  ('red apple', '🍎'),
  ('pear', '🍐'),
  ('orange', '🍊'),
  ('lemon', '🍋'),
  ('banana', '🍌'),
  ('watermelon', '🍉'),
  ('grapes', '🍇'),
  ('strawberry', '🍓'),
  ('blueberries', '🫐'),
  ('melon', '🍈'),
  ('cherries', '🍒'),
  ('peach', '🍑'),
  ('mango', '🥭'),
  ('pineapple', '🍍'),
  ('coconut', '🥥'),
  ('kiwi', '🥝'),
  ('tomato', '🍅'),
  ('eggplant', '🍆'),
  ('avocado', '🥑'),
  ('broccoli', '🥦'),
  ('leafy green', '🥬'),
  ('cucumber', '🥒'),
  ('hot pepper', '🌶️'),
  ('corn', '🌽'),
  ('carrot', '🥕'),
  ('garlic', '🧄'),
  ('onion', '🧅'),
  ('potato', '🥔'),
  ('sweet potato', '🍠'),
  ('croissant', '🥐'),
  ('bagel', '🥯'),
  ('bread', '🍞'),
  ('baguette', '🥖'),
  ('pretzel', '🥨'),
  ('cheese', '🧀'),
  ('egg', '🥚'),
  ('fried egg', '🍳'),
  ('pancakes', '🥞'),
  ('waffle', '🧇'),
  ('bacon', '🥓'),
  ('steak', '🥩'),
  ('poultry leg', '🍗'),
  ('meat on bone', '🍖'),
  ('hotdog', '🌭'),
  ('burger', '🍔'),
  ('fries', '🍟'),
  ('pizza', '🍕'),
  ('sandwich', '🥪'),
  ('taco', '🌮'),
  ('burrito', '🌯'),
  ('stuffed flatbread', '🥙'),
  ('bento', '🍱'),
  ('stew', '🍲'),
  ('spaghetti', '🍝'),
  ('ramen', '🍜'),
  ('sushi', '🍣'),
  ('fried shrimp', '🍤'),
  ('rice ball', '🍙'),
  ('rice', '🍚'),
  ('shallow pan', '🥘'),
  ('oden', '🍢'),
  ('takeout', '🥡'),
  ('soft ice cream', '🍦'),
  ('ice cream', '🍨'),
  ('shaved ice', '🍧'),
  ('donut', '🍩'),
  ('cookie', '🍪'),
  ('birthday cake', '🎂'),
  ('cake', '🍰'),
  ('cupcake', '🧁'),
  ('pie', '🥧'),
  ('chocolate', '🍫'),
  ('candy', '🍬'),
  ('lollipop', '🍭'),
  ('honey', '🍯'),
  ('baby bottle', '🍼'),
  ('milk', '🥛'),
  ('coffee', '☕'),
  ('teapot', '🫖'),
  ('tea', '🍵'),
  ('sake', '🍶'),
  ('champagne', '🍾'),
  ('wine', '🍷'),
  ('cocktail', '🍸'),
  ('tropical drink', '🍹'),
  ('beer', '🍺'),
  ('clink beers', '🍻'),
  ('clink glasses', '🥂'),
  ('tumbler', '🥃'),
  ('soccer', '⚽'),
  ('basketball', '🏀'),
  ('football', '🏈'),
  ('baseball', '⚾'),
  ('softball', '🥎'),
  ('tennis', '🎾'),
  ('volleyball', '🏐'),
  ('rugby', '🏉'),
  ('frisbee', '🥏'),
  ('pool 8 ball', '🎱'),
  ('yo-yo', '🪀'),
  ('ping pong', '🏓'),
  ('badminton', '🏸'),
  ('goal', '🥅'),
  ('ice hockey', '🏒'),
  ('field hockey', '🏑'),
  ('lacrosse', '🥍'),
  ('cricket', '🏏'),
  ('golf', '⛳'),
  ('bow and arrow', '🏹'),
  ('fishing', '🎣'),
  ('boxing', '🥊'),
  ('martial arts', '🥋'),
  ('running shirt', '🎽'),
  ('skateboard', '🛹'),
  ('roller skate', '🛼'),
  ('sled', '🛷'),
  ('ice skate', '⛸️'),
  ('ski', '🎿'),
  ('snowboarder', '🏂'),
  ('parachute', '🪂'),
  ('weight lifter', '🏋️'),
  ('fencer', '🤺'),
  ('handball', '🤾'),
  ('golfer', '🏌️'),
  ('horse racing', '🏇'),
  ('yoga', '🧘'),
  ('surfer', '🏄'),
  ('swimmer', '🏊'),
  ('cyclist', '🚴'),
  ('video game', '🎮'),
  ('joystick', '🕹️'),
  ('slot machine', '🎰'),
  ('die', '🎲'),
  ('puzzle', '🧩'),
  ('chess pawn', '♟️'),
  ('bullseye', '🎯'),
  ('bowling', '🎳'),
  ('microphone', '🎤'),
  ('headphones', '🎧'),
  ('saxophone', '🎷'),
  ('guitar', '🎸'),
  ('piano', '🎹'),
  ('trumpet', '🎺'),
  ('violin', '🎻'),
  ('drum', '🥁'),
  ('banjo', '🪕'),
  ('clapper', '🎬'),
  ('artist palette', '🎨'),
  ('pencil', '✏️'),
  ('books', '📚'),
  ('open book', '📖'),
  ('memo', '📝'),
  ('microscope', '🔬'),
  ('telescope', '🔭'),
  ('lightbulb', '💡'),
  ('key', '🔑'),
  ('locked', '🔒'),
  ('unlocked', '🔓'),
  ('alarm', '⏰'),
  ('hourglass', '⏳'),
  ('gem', '💎'),
  ('money bag', '💰'),
  ('dollar', '💵'),
  ('credit card', '💳'),
  ('gift', '🎁'),
  ('party popper', '🎉'),
  ('confetti', '🎊'),
  ('balloon', '🎈'),
  ('ribbon', '🎀'),
  ('jack o lantern', '🎃'),
  ('christmas tree', '🎄'),
  ('piñata', '🪅'),
  ('camera', '📷'),
  ('video camera', '📹'),
  ('tv', '📺'),
  ('phone', '📱'),
  ('laptop', '💻'),
  ('desktop', '🖥️'),
  ('keyboard', '⌨️'),
  ('mouse computer', '🖱️'),
  ('floppy disk', '💾'),
  ('cd', '💿'),
  ('dvd', '📀'),
  ('car', '🚗'),
  ('taxi', '🚕'),
  ('suv', '🚙'),
  ('bus', '🚌'),
  ('trolley', '🚎'),
  ('race car', '🏎️'),
  ('police car', '🚓'),
  ('ambulance', '🚑'),
  ('fire engine', '🚒'),
  ('minibus', '🚐'),
  ('pickup', '🛻'),
  ('truck', '🚚'),
  ('semi', '🚛'),
  ('motorcycle', '🏍️'),
  ('scooter', '🛵'),
  ('bike', '🚲'),
  ('kick scooter', '🛴'),
  ('police light', '🚨'),
  ('police car oncoming', '🚔'),
  ('bus oncoming', '🚍'),
  ('taxi oncoming', '🚖'),
  ('train', '🚆'),
  ('metro', '🚇'),
  ('tram', '🚊'),
  ('station', '🚉'),
  ('plane', '✈️'),
  ('departing', '🛫'),
  ('landing', '🛬'),
  ('small plane', '🛩️'),
  ('rocket', '🚀'),
  ('ufo', '🛸'),
  ('helicopter', '🚁'),
  ('sailboat', '⛵'),
  ('speedboat', '🚤'),
  ('motor boat', '🛥️'),
  ('passenger ship', '🛳️'),
  ('ferry', '⛴️'),
  ('ship', '🚢'),
  ('anchor', '⚓'),
  ('house', '🏠'),
  ('house garden', '🏡'),
  ('office', '🏢'),
  ('department store', '🏬'),
  ('post office', '🏣'),
  ('hospital', '🏥'),
  ('bank', '🏦'),
  ('hotel', '🏨'),
  ('convenience', '🏪'),
  ('school', '🏫'),
  ('classical building', '🏛️'),
  ('church', '⛪'),
  ('mosque', '🕌'),
  ('synagogue', '🕍'),
  ('temple', '🛕'),
  ('castle japan', '🏯'),
  ('castle', '🏰'),
  ('tokyo tower', '🗼'),
  ('statue of liberty', '🗽'),
  ('shrine', '⛩️'),
  ('foggy city', '🌁'),
  ('night stars', '🌃'),
  ('sunrise mountains', '🌄'),
  ('sunrise', '🌅'),
  ('sunset city', '🌆'),
  ('sunset', '🌇'),
  ('bridge night', '🌉'),
  ('volcano', '🌋'),
  ('mount fuji', '🗻'),
  ('snowy mountain', '🏔️'),
  ('mountain', '⛰️'),
  ('beach', '🏖️'),
  ('desert island', '🏝️'),
  ('earth africa', '🌍'),
  ('earth americas', '🌎'),
  ('earth asia', '🌏'),
  ('red heart', '❤️'),
  ('orange heart', '🧡'),
  ('yellow heart', '💛'),
  ('green heart', '💚'),
  ('blue heart', '💙'),
  ('purple heart', '💜'),
  ('black heart', '🖤'),
  ('white heart', '🤍'),
  ('brown heart', '🤎'),
  ('broken heart', '💔'),
  ('heart exclamation', '❣️'),
  ('two hearts', '💕'),
  ('revolving hearts', '💞'),
  ('beating heart', '💓'),
  ('growing heart', '💗'),
  ('sparkling heart', '💖'),
  ('heart arrow', '💘'),
  ('gift heart', '💝'),
  ('spade heart', '♥️'),
  ('spades', '♠️'),
  ('clubs', '♣️'),
  ('diamonds', '♦️'),
  ('peace', '☮️'),
  ('cross', '✝️'),
  ('star and crescent', '☪️'),
  ('dharma', '☸️'),
  ('star of david', '✡️'),
  ('yin yang', '☯️'),
  ('om', '🕉️'),
  ('orthodox cross', '☦️'),
  ('atom', '⚛️'),
  ('radioactive', '☢️'),
  ('biohazard', '☣️'),
  ('recycle', '♻️'),
  ('ok square', '🆗'),
  ('new', '🆕'),
  ('cool', '🆒'),
  ('free', '🆓'),
  ('up', '🆙'),
  ('top', '🔝'),
  ('end', '🔚'),
  ('on', '🔛'),
  ('back', '🔙'),
  ('soon', '🔜'),
  ('check', '✅'),
  ('cross mark', '❌'),
  ('circle red', '⭕'),
  ('no entry', '🚫'),
  ('exclamation', '❗'),
  ('question', '❓'),
  ('white exclamation', '❕'),
  ('white question', '❔'),
  ('double exclamation', '‼️'),
  ('warning', '⚠️'),
  ('children crossing', '🚸'),
  ('fleur de lis', '⚜️'),
  ('trident', '🔱'),
  ('name badge', '📛'),
  ('japanese symbol for beginner', '🔰'),
  ('aries', '♈'),
  ('taurus', '♉'),
  ('gemini', '♊'),
  ('cancer', '♋'),
  ('leo', '♌'),
  ('virgo', '♍'),
  ('libra', '♎'),
  ('scorpio', '♏'),
  ('sagittarius', '♐'),
  ('capricorn', '♑'),
  ('aquarius', '♒'),
  ('pisces', '♓'),
  ('ophiuchus', '⛎'),
  ('six pointed star', '🔯'),
  ('sparkle', '❇️'),
  ('eight spoked asterisk', '✳️'),
  ('eight pointed star', '✴️'),
  ('globe meridians', '🌐'),
  ('radio button', '🔘'),
  ('black square', '🔲'),
  ('white square', '🔳'),
  ('black circle', '⚫'),
  ('white circle', '⚪'),
  ('green circle', '🟢'),
  ('yellow circle', '🟡'),
  ('orange circle', '🟠'),
  ('red circle', '🔴'),
  ('blue circle', '🔵'),
  ('purple circle', '🟣'),
  ('brown circle', '🟤'),
  ('black large square', '⬛'),
  ('white large square', '⬜'),
  ('red square', '🟥'),
  ('orange square', '🟧'),
  ('yellow square', '🟨'),
  ('green square', '🟩'),
  ('blue square', '🟦'),
  ('purple square', '🟪'),
  ('brown square', '🟫')
)
UPDATE OR IGNORE `message_reactions`
   SET `unicode_char` = (
         SELECT `char` FROM name_to_char
          WHERE name_to_char.`name` = `message_reactions`.`unicode_char`
       )
 WHERE `unicode_char` IN (SELECT `name` FROM name_to_char);
--> statement-breakpoint

-- Sweep any row left behind by the OR IGNORE — it didn't migrate
-- because a correct row already existed for the same target + user.
WITH name_to_char(name, char) AS (VALUES
  ('grinning', '😀'),
  ('smiley', '😃'),
  ('smile', '😄'),
  ('grin', '😁'),
  ('laughing', '😆'),
  ('sweat smile', '😅'),
  ('rofl', '🤣'),
  ('joy', '😂'),
  ('slight smile', '🙂'),
  ('upside down', '🙃'),
  ('wink', '😉'),
  ('blush', '😊'),
  ('innocent', '😇'),
  ('smiling hearts', '🥰'),
  ('heart eyes', '😍'),
  ('star struck', '🤩'),
  ('blowing kiss', '😘'),
  ('kissing', '😗'),
  ('kissing closed eyes', '😚'),
  ('kissing smile', '😙'),
  ('smiling tear', '🥲'),
  ('yum', '😋'),
  ('tongue', '😛'),
  ('winking tongue', '😜'),
  ('zany', '🤪'),
  ('squint tongue', '😝'),
  ('money mouth', '🤑'),
  ('hug', '🤗'),
  ('hand over mouth', '🤭'),
  ('shushing', '🤫'),
  ('thinking', '🤔'),
  ('zipper mouth', '🤐'),
  ('raised brow', '🤨'),
  ('neutral', '😐'),
  ('expressionless', '😑'),
  ('no mouth', '😶'),
  ('smirk', '😏'),
  ('unamused', '😒'),
  ('eye roll', '🙄'),
  ('grimace', '😬'),
  ('lying', '🤥'),
  ('relieved', '😌'),
  ('pensive', '😔'),
  ('sleepy', '😪'),
  ('drooling', '🤤'),
  ('sleeping', '😴'),
  ('mask', '😷'),
  ('fever', '🤒'),
  ('head bandage', '🤕'),
  ('nauseated', '🤢'),
  ('vomit', '🤮'),
  ('sneeze', '🤧'),
  ('hot', '🥵'),
  ('cold', '🥶'),
  ('woozy', '🥴'),
  ('dizzy', '😵'),
  ('mind blown', '🤯'),
  ('cowboy', '🤠'),
  ('party', '🥳'),
  ('disguise', '🥸'),
  ('sunglasses', '😎'),
  ('nerd', '🤓'),
  ('monocle', '🧐'),
  ('confused', '😕'),
  ('worried', '😟'),
  ('slight frown', '🙁'),
  ('frown', '☹️'),
  ('open mouth', '😮'),
  ('hushed', '😯'),
  ('astonished', '😲'),
  ('flushed', '😳'),
  ('pleading', '🥺'),
  ('frowning open', '😦'),
  ('anguished', '😧'),
  ('fearful', '😨'),
  ('anxious sweat', '😰'),
  ('sad sweat', '😥'),
  ('cry', '😢'),
  ('loudly crying', '😭'),
  ('scream', '😱'),
  ('confounded', '😖'),
  ('persevere', '😣'),
  ('disappointed', '😞'),
  ('downcast sweat', '😓'),
  ('weary', '😩'),
  ('tired', '😫'),
  ('yawn', '🥱'),
  ('triumph', '😤'),
  ('rage', '😡'),
  ('angry', '😠'),
  ('swearing', '🤬'),
  ('imp', '😈'),
  ('angry imp', '👿'),
  ('skull', '💀'),
  ('poop', '💩'),
  ('clown', '🤡'),
  ('ogre', '👹'),
  ('goblin', '👺'),
  ('ghost', '👻'),
  ('alien', '👽'),
  ('space invader', '👾'),
  ('robot', '🤖'),
  ('100', '💯'),
  ('anger', '💢'),
  ('boom', '💥'),
  ('dizzy stars', '💫'),
  ('sweat drops', '💦'),
  ('dash', '💨'),
  ('hole', '🕳️'),
  ('bomb', '💣'),
  ('speech bubble', '💬'),
  ('thought bubble', '💭'),
  ('zzz', '💤'),
  ('wave', '👋'),
  ('raised back of hand', '🤚'),
  ('splayed hand', '🖐️'),
  ('raised hand', '✋'),
  ('vulcan', '🖖'),
  ('ok hand', '👌'),
  ('pinched fingers', '🤌'),
  ('pinching', '🤏'),
  ('victory', '✌️'),
  ('fingers crossed', '🤞'),
  ('love you', '🤟'),
  ('rock on', '🤘'),
  ('call me', '🤙'),
  ('left point', '👈'),
  ('right point', '👉'),
  ('up point', '👆'),
  ('middle finger', '🖕'),
  ('down point', '👇'),
  ('index up', '☝️'),
  ('thumbs up', '👍'),
  ('thumbs down', '👎'),
  ('fist', '✊'),
  ('punch', '👊'),
  ('left fist', '🤛'),
  ('right fist', '🤜'),
  ('clap', '👏'),
  ('raised hands', '🙌'),
  ('open hands', '👐'),
  ('palms up', '🤲'),
  ('handshake', '🤝'),
  ('pray', '🙏'),
  ('nail polish', '💅'),
  ('selfie', '🤳'),
  ('flex', '💪'),
  ('robotic arm', '🦾'),
  ('eyes', '👀'),
  ('eye', '👁️'),
  ('tongue', '👅'),
  ('lips', '👄'),
  ('brain', '🧠'),
  ('anatomical heart', '🫀'),
  ('bone', '🦴'),
  ('baby', '👶'),
  ('child', '🧒'),
  ('boy', '👦'),
  ('girl', '👧'),
  ('person', '🧑'),
  ('man', '👨'),
  ('woman', '👩'),
  ('older person', '🧓'),
  ('old man', '👴'),
  ('old woman', '👵'),
  ('bowing', '🙇'),
  ('facepalm', '🤦'),
  ('shrug', '🤷'),
  ('dancing', '💃'),
  ('man dancing', '🕺'),
  ('walking', '🚶'),
  ('running', '🏃'),
  ('dog', '🐶'),
  ('cat', '🐱'),
  ('mouse', '🐭'),
  ('hamster', '🐹'),
  ('rabbit', '🐰'),
  ('fox', '🦊'),
  ('bear', '🐻'),
  ('panda', '🐼'),
  ('koala', '🐨'),
  ('tiger', '🐯'),
  ('lion', '🦁'),
  ('cow', '🐮'),
  ('pig', '🐷'),
  ('frog', '🐸'),
  ('monkey face', '🐵'),
  ('see no evil', '🙈'),
  ('hear no evil', '🙉'),
  ('speak no evil', '🙊'),
  ('monkey', '🐒'),
  ('chicken', '🐔'),
  ('penguin', '🐧'),
  ('bird', '🐦'),
  ('chick', '🐤'),
  ('duck', '🦆'),
  ('eagle', '🦅'),
  ('owl', '🦉'),
  ('bat', '🦇'),
  ('wolf', '🐺'),
  ('boar', '🐗'),
  ('horse face', '🐴'),
  ('unicorn', '🦄'),
  ('bee', '🐝'),
  ('bug', '🐛'),
  ('butterfly', '🦋'),
  ('snail', '🐌'),
  ('ladybug', '🐞'),
  ('turtle', '🐢'),
  ('snake', '🐍'),
  ('lizard', '🦎'),
  ('octopus', '🐙'),
  ('squid', '🦑'),
  ('shrimp', '🦐'),
  ('lobster', '🦞'),
  ('crab', '🦀'),
  ('fish', '🐟'),
  ('dolphin', '🐬'),
  ('whale', '🐳'),
  ('shark', '🦈'),
  ('crocodile', '🐊'),
  ('tiger body', '🐅'),
  ('leopard', '🐆'),
  ('zebra', '🦓'),
  ('gorilla', '🦍'),
  ('elephant', '🐘'),
  ('rhino', '🦏'),
  ('hippo', '🦛'),
  ('camel', '🐪'),
  ('two hump camel', '🐫'),
  ('giraffe', '🦒'),
  ('kangaroo', '🦘'),
  ('horse', '🐎'),
  ('pig body', '🐖'),
  ('ox', '🐂'),
  ('sheep', '🐑'),
  ('goat', '🐐'),
  ('deer', '🦌'),
  ('dog body', '🐕'),
  ('poodle', '🐩'),
  ('guide dog', '🦮'),
  ('cat body', '🐈'),
  ('rooster', '🐓'),
  ('turkey', '🦃'),
  ('peacock', '🦚'),
  ('parrot', '🦜'),
  ('tree', '🌳'),
  ('evergreen', '🌲'),
  ('palm tree', '🌴'),
  ('cactus', '🌵'),
  ('tulip', '🌷'),
  ('rose', '🌹'),
  ('wilted rose', '🥀'),
  ('hibiscus', '🌺'),
  ('cherry blossom', '🌸'),
  ('blossom', '🌼'),
  ('sunflower', '🌻'),
  ('sun', '☀️'),
  ('full moon face', '🌝'),
  ('new moon face', '🌚'),
  ('crescent moon', '🌙'),
  ('star', '⭐'),
  ('glowing star', '🌟'),
  ('sparkles', '✨'),
  ('lightning', '⚡'),
  ('fire', '🔥'),
  ('rainbow', '🌈'),
  ('cloud', '☁️'),
  ('snowflake', '❄️'),
  ('umbrella rain', '☔'),
  ('wave water', '🌊'),
  ('red apple', '🍎'),
  ('pear', '🍐'),
  ('orange', '🍊'),
  ('lemon', '🍋'),
  ('banana', '🍌'),
  ('watermelon', '🍉'),
  ('grapes', '🍇'),
  ('strawberry', '🍓'),
  ('blueberries', '🫐'),
  ('melon', '🍈'),
  ('cherries', '🍒'),
  ('peach', '🍑'),
  ('mango', '🥭'),
  ('pineapple', '🍍'),
  ('coconut', '🥥'),
  ('kiwi', '🥝'),
  ('tomato', '🍅'),
  ('eggplant', '🍆'),
  ('avocado', '🥑'),
  ('broccoli', '🥦'),
  ('leafy green', '🥬'),
  ('cucumber', '🥒'),
  ('hot pepper', '🌶️'),
  ('corn', '🌽'),
  ('carrot', '🥕'),
  ('garlic', '🧄'),
  ('onion', '🧅'),
  ('potato', '🥔'),
  ('sweet potato', '🍠'),
  ('croissant', '🥐'),
  ('bagel', '🥯'),
  ('bread', '🍞'),
  ('baguette', '🥖'),
  ('pretzel', '🥨'),
  ('cheese', '🧀'),
  ('egg', '🥚'),
  ('fried egg', '🍳'),
  ('pancakes', '🥞'),
  ('waffle', '🧇'),
  ('bacon', '🥓'),
  ('steak', '🥩'),
  ('poultry leg', '🍗'),
  ('meat on bone', '🍖'),
  ('hotdog', '🌭'),
  ('burger', '🍔'),
  ('fries', '🍟'),
  ('pizza', '🍕'),
  ('sandwich', '🥪'),
  ('taco', '🌮'),
  ('burrito', '🌯'),
  ('stuffed flatbread', '🥙'),
  ('bento', '🍱'),
  ('stew', '🍲'),
  ('spaghetti', '🍝'),
  ('ramen', '🍜'),
  ('sushi', '🍣'),
  ('fried shrimp', '🍤'),
  ('rice ball', '🍙'),
  ('rice', '🍚'),
  ('shallow pan', '🥘'),
  ('oden', '🍢'),
  ('takeout', '🥡'),
  ('soft ice cream', '🍦'),
  ('ice cream', '🍨'),
  ('shaved ice', '🍧'),
  ('donut', '🍩'),
  ('cookie', '🍪'),
  ('birthday cake', '🎂'),
  ('cake', '🍰'),
  ('cupcake', '🧁'),
  ('pie', '🥧'),
  ('chocolate', '🍫'),
  ('candy', '🍬'),
  ('lollipop', '🍭'),
  ('honey', '🍯'),
  ('baby bottle', '🍼'),
  ('milk', '🥛'),
  ('coffee', '☕'),
  ('teapot', '🫖'),
  ('tea', '🍵'),
  ('sake', '🍶'),
  ('champagne', '🍾'),
  ('wine', '🍷'),
  ('cocktail', '🍸'),
  ('tropical drink', '🍹'),
  ('beer', '🍺'),
  ('clink beers', '🍻'),
  ('clink glasses', '🥂'),
  ('tumbler', '🥃'),
  ('soccer', '⚽'),
  ('basketball', '🏀'),
  ('football', '🏈'),
  ('baseball', '⚾'),
  ('softball', '🥎'),
  ('tennis', '🎾'),
  ('volleyball', '🏐'),
  ('rugby', '🏉'),
  ('frisbee', '🥏'),
  ('pool 8 ball', '🎱'),
  ('yo-yo', '🪀'),
  ('ping pong', '🏓'),
  ('badminton', '🏸'),
  ('goal', '🥅'),
  ('ice hockey', '🏒'),
  ('field hockey', '🏑'),
  ('lacrosse', '🥍'),
  ('cricket', '🏏'),
  ('golf', '⛳'),
  ('bow and arrow', '🏹'),
  ('fishing', '🎣'),
  ('boxing', '🥊'),
  ('martial arts', '🥋'),
  ('running shirt', '🎽'),
  ('skateboard', '🛹'),
  ('roller skate', '🛼'),
  ('sled', '🛷'),
  ('ice skate', '⛸️'),
  ('ski', '🎿'),
  ('snowboarder', '🏂'),
  ('parachute', '🪂'),
  ('weight lifter', '🏋️'),
  ('fencer', '🤺'),
  ('handball', '🤾'),
  ('golfer', '🏌️'),
  ('horse racing', '🏇'),
  ('yoga', '🧘'),
  ('surfer', '🏄'),
  ('swimmer', '🏊'),
  ('cyclist', '🚴'),
  ('video game', '🎮'),
  ('joystick', '🕹️'),
  ('slot machine', '🎰'),
  ('die', '🎲'),
  ('puzzle', '🧩'),
  ('chess pawn', '♟️'),
  ('bullseye', '🎯'),
  ('bowling', '🎳'),
  ('microphone', '🎤'),
  ('headphones', '🎧'),
  ('saxophone', '🎷'),
  ('guitar', '🎸'),
  ('piano', '🎹'),
  ('trumpet', '🎺'),
  ('violin', '🎻'),
  ('drum', '🥁'),
  ('banjo', '🪕'),
  ('clapper', '🎬'),
  ('artist palette', '🎨'),
  ('pencil', '✏️'),
  ('books', '📚'),
  ('open book', '📖'),
  ('memo', '📝'),
  ('microscope', '🔬'),
  ('telescope', '🔭'),
  ('lightbulb', '💡'),
  ('key', '🔑'),
  ('locked', '🔒'),
  ('unlocked', '🔓'),
  ('alarm', '⏰'),
  ('hourglass', '⏳'),
  ('gem', '💎'),
  ('money bag', '💰'),
  ('dollar', '💵'),
  ('credit card', '💳'),
  ('gift', '🎁'),
  ('party popper', '🎉'),
  ('confetti', '🎊'),
  ('balloon', '🎈'),
  ('ribbon', '🎀'),
  ('jack o lantern', '🎃'),
  ('christmas tree', '🎄'),
  ('piñata', '🪅'),
  ('camera', '📷'),
  ('video camera', '📹'),
  ('tv', '📺'),
  ('phone', '📱'),
  ('laptop', '💻'),
  ('desktop', '🖥️'),
  ('keyboard', '⌨️'),
  ('mouse computer', '🖱️'),
  ('floppy disk', '💾'),
  ('cd', '💿'),
  ('dvd', '📀'),
  ('car', '🚗'),
  ('taxi', '🚕'),
  ('suv', '🚙'),
  ('bus', '🚌'),
  ('trolley', '🚎'),
  ('race car', '🏎️'),
  ('police car', '🚓'),
  ('ambulance', '🚑'),
  ('fire engine', '🚒'),
  ('minibus', '🚐'),
  ('pickup', '🛻'),
  ('truck', '🚚'),
  ('semi', '🚛'),
  ('motorcycle', '🏍️'),
  ('scooter', '🛵'),
  ('bike', '🚲'),
  ('kick scooter', '🛴'),
  ('police light', '🚨'),
  ('police car oncoming', '🚔'),
  ('bus oncoming', '🚍'),
  ('taxi oncoming', '🚖'),
  ('train', '🚆'),
  ('metro', '🚇'),
  ('tram', '🚊'),
  ('station', '🚉'),
  ('plane', '✈️'),
  ('departing', '🛫'),
  ('landing', '🛬'),
  ('small plane', '🛩️'),
  ('rocket', '🚀'),
  ('ufo', '🛸'),
  ('helicopter', '🚁'),
  ('sailboat', '⛵'),
  ('speedboat', '🚤'),
  ('motor boat', '🛥️'),
  ('passenger ship', '🛳️'),
  ('ferry', '⛴️'),
  ('ship', '🚢'),
  ('anchor', '⚓'),
  ('house', '🏠'),
  ('house garden', '🏡'),
  ('office', '🏢'),
  ('department store', '🏬'),
  ('post office', '🏣'),
  ('hospital', '🏥'),
  ('bank', '🏦'),
  ('hotel', '🏨'),
  ('convenience', '🏪'),
  ('school', '🏫'),
  ('classical building', '🏛️'),
  ('church', '⛪'),
  ('mosque', '🕌'),
  ('synagogue', '🕍'),
  ('temple', '🛕'),
  ('castle japan', '🏯'),
  ('castle', '🏰'),
  ('tokyo tower', '🗼'),
  ('statue of liberty', '🗽'),
  ('shrine', '⛩️'),
  ('foggy city', '🌁'),
  ('night stars', '🌃'),
  ('sunrise mountains', '🌄'),
  ('sunrise', '🌅'),
  ('sunset city', '🌆'),
  ('sunset', '🌇'),
  ('bridge night', '🌉'),
  ('volcano', '🌋'),
  ('mount fuji', '🗻'),
  ('snowy mountain', '🏔️'),
  ('mountain', '⛰️'),
  ('beach', '🏖️'),
  ('desert island', '🏝️'),
  ('earth africa', '🌍'),
  ('earth americas', '🌎'),
  ('earth asia', '🌏'),
  ('red heart', '❤️'),
  ('orange heart', '🧡'),
  ('yellow heart', '💛'),
  ('green heart', '💚'),
  ('blue heart', '💙'),
  ('purple heart', '💜'),
  ('black heart', '🖤'),
  ('white heart', '🤍'),
  ('brown heart', '🤎'),
  ('broken heart', '💔'),
  ('heart exclamation', '❣️'),
  ('two hearts', '💕'),
  ('revolving hearts', '💞'),
  ('beating heart', '💓'),
  ('growing heart', '💗'),
  ('sparkling heart', '💖'),
  ('heart arrow', '💘'),
  ('gift heart', '💝'),
  ('spade heart', '♥️'),
  ('spades', '♠️'),
  ('clubs', '♣️'),
  ('diamonds', '♦️'),
  ('peace', '☮️'),
  ('cross', '✝️'),
  ('star and crescent', '☪️'),
  ('dharma', '☸️'),
  ('star of david', '✡️'),
  ('yin yang', '☯️'),
  ('om', '🕉️'),
  ('orthodox cross', '☦️'),
  ('atom', '⚛️'),
  ('radioactive', '☢️'),
  ('biohazard', '☣️'),
  ('recycle', '♻️'),
  ('ok square', '🆗'),
  ('new', '🆕'),
  ('cool', '🆒'),
  ('free', '🆓'),
  ('up', '🆙'),
  ('top', '🔝'),
  ('end', '🔚'),
  ('on', '🔛'),
  ('back', '🔙'),
  ('soon', '🔜'),
  ('check', '✅'),
  ('cross mark', '❌'),
  ('circle red', '⭕'),
  ('no entry', '🚫'),
  ('exclamation', '❗'),
  ('question', '❓'),
  ('white exclamation', '❕'),
  ('white question', '❔'),
  ('double exclamation', '‼️'),
  ('warning', '⚠️'),
  ('children crossing', '🚸'),
  ('fleur de lis', '⚜️'),
  ('trident', '🔱'),
  ('name badge', '📛'),
  ('japanese symbol for beginner', '🔰'),
  ('aries', '♈'),
  ('taurus', '♉'),
  ('gemini', '♊'),
  ('cancer', '♋'),
  ('leo', '♌'),
  ('virgo', '♍'),
  ('libra', '♎'),
  ('scorpio', '♏'),
  ('sagittarius', '♐'),
  ('capricorn', '♑'),
  ('aquarius', '♒'),
  ('pisces', '♓'),
  ('ophiuchus', '⛎'),
  ('six pointed star', '🔯'),
  ('sparkle', '❇️'),
  ('eight spoked asterisk', '✳️'),
  ('eight pointed star', '✴️'),
  ('globe meridians', '🌐'),
  ('radio button', '🔘'),
  ('black square', '🔲'),
  ('white square', '🔳'),
  ('black circle', '⚫'),
  ('white circle', '⚪'),
  ('green circle', '🟢'),
  ('yellow circle', '🟡'),
  ('orange circle', '🟠'),
  ('red circle', '🔴'),
  ('blue circle', '🔵'),
  ('purple circle', '🟣'),
  ('brown circle', '🟤'),
  ('black large square', '⬛'),
  ('white large square', '⬜'),
  ('red square', '🟥'),
  ('orange square', '🟧'),
  ('yellow square', '🟨'),
  ('green square', '🟩'),
  ('blue square', '🟦'),
  ('purple square', '🟪'),
  ('brown square', '🟫')
)
DELETE FROM `message_reactions`
 WHERE `unicode_char` IN (SELECT `name` FROM name_to_char);
