/**
 * Curated subset of the Unicode 15 emoji catalog, grouped by category
 * for the picker UI. This is intentionally NOT the full catalog (~3700
 * entries) — that would bundle ~120KB just for picker labels — instead
 * it's the ~400 most-used emoji across the categories Discord and
 * Messenger surface by default.
 *
 * Each entry carries:
 *   - `char`: the actual Unicode codepoint(s). What gets inserted into
 *     the composer and rendered by the browser's native emoji font.
 *   - `name`: short search label for the typeahead. Lowercase, ASCII.
 *   - `tags`: extra search aliases ("grinning" → ["happy", "smile"])
 *     so users searching common synonyms still find the emoji.
 *
 * Adding emoji: drop entries into the matching category array. Keep
 * `name` and `tags` lowercase. Skin-tone variants are deliberately
 * NOT enumerated — users who need them can copy/paste from a system
 * picker. This subset trades catalog completeness for picker speed.
 */

export interface UnicodeEmoji {
  char: string;
  name: string;
  tags?: readonly string[];
}

export interface UnicodeEmojiCategory {
  id: string;
  label: string;
  emoji: readonly UnicodeEmoji[];
}

export const UNICODE_EMOJI_CATEGORIES: readonly UnicodeEmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys & emotion",
    emoji: [
      { char: "😀", name: "grinning", tags: ["happy", "smile"] },
      { char: "😃", name: "smiley", tags: ["happy", "joy"] },
      { char: "😄", name: "smile", tags: ["happy", "joy"] },
      { char: "😁", name: "grin", tags: ["happy", "teeth"] },
      { char: "😆", name: "laughing", tags: ["lol"] },
      { char: "😅", name: "sweat smile", tags: ["nervous"] },
      { char: "🤣", name: "rofl", tags: ["lol", "rolling"] },
      { char: "😂", name: "joy", tags: ["lol", "crying laughing"] },
      { char: "🙂", name: "slight smile" },
      { char: "🙃", name: "upside down", tags: ["sarcasm"] },
      { char: "😉", name: "wink" },
      { char: "😊", name: "blush", tags: ["smile"] },
      { char: "😇", name: "innocent", tags: ["halo", "angel"] },
      { char: "🥰", name: "smiling hearts", tags: ["love"] },
      { char: "😍", name: "heart eyes", tags: ["love"] },
      { char: "🤩", name: "star struck", tags: ["wow"] },
      { char: "😘", name: "blowing kiss", tags: ["love"] },
      { char: "😗", name: "kissing" },
      { char: "😚", name: "kissing closed eyes" },
      { char: "😙", name: "kissing smile" },
      { char: "🥲", name: "smiling tear" },
      { char: "😋", name: "yum", tags: ["delicious"] },
      { char: "😛", name: "tongue" },
      { char: "😜", name: "winking tongue" },
      { char: "🤪", name: "zany" },
      { char: "😝", name: "squint tongue" },
      { char: "🤑", name: "money mouth" },
      { char: "🤗", name: "hug" },
      { char: "🤭", name: "hand over mouth" },
      { char: "🤫", name: "shushing", tags: ["quiet"] },
      { char: "🤔", name: "thinking" },
      { char: "🤐", name: "zipper mouth" },
      { char: "🤨", name: "raised brow" },
      { char: "😐", name: "neutral" },
      { char: "😑", name: "expressionless" },
      { char: "😶", name: "no mouth" },
      { char: "😏", name: "smirk" },
      { char: "😒", name: "unamused" },
      { char: "🙄", name: "eye roll" },
      { char: "😬", name: "grimace" },
      { char: "🤥", name: "lying" },
      { char: "😌", name: "relieved" },
      { char: "😔", name: "pensive", tags: ["sad"] },
      { char: "😪", name: "sleepy" },
      { char: "🤤", name: "drooling" },
      { char: "😴", name: "sleeping" },
      { char: "😷", name: "mask" },
      { char: "🤒", name: "fever" },
      { char: "🤕", name: "head bandage", tags: ["hurt"] },
      { char: "🤢", name: "nauseated", tags: ["sick"] },
      { char: "🤮", name: "vomit" },
      { char: "🤧", name: "sneeze" },
      { char: "🥵", name: "hot" },
      { char: "🥶", name: "cold" },
      { char: "🥴", name: "woozy" },
      { char: "😵", name: "dizzy" },
      { char: "🤯", name: "mind blown" },
      { char: "🤠", name: "cowboy" },
      { char: "🥳", name: "party", tags: ["celebrate"] },
      { char: "🥸", name: "disguise" },
      { char: "😎", name: "sunglasses", tags: ["cool"] },
      { char: "🤓", name: "nerd" },
      { char: "🧐", name: "monocle" },
      { char: "😕", name: "confused" },
      { char: "😟", name: "worried" },
      { char: "🙁", name: "slight frown" },
      { char: "☹️", name: "frown" },
      { char: "😮", name: "open mouth" },
      { char: "😯", name: "hushed" },
      { char: "😲", name: "astonished" },
      { char: "😳", name: "flushed" },
      { char: "🥺", name: "pleading", tags: ["puppy eyes"] },
      { char: "😦", name: "frowning open" },
      { char: "😧", name: "anguished" },
      { char: "😨", name: "fearful" },
      { char: "😰", name: "anxious sweat" },
      { char: "😥", name: "sad sweat" },
      { char: "😢", name: "cry" },
      { char: "😭", name: "loudly crying", tags: ["sob"] },
      { char: "😱", name: "scream" },
      { char: "😖", name: "confounded" },
      { char: "😣", name: "persevere" },
      { char: "😞", name: "disappointed" },
      { char: "😓", name: "downcast sweat" },
      { char: "😩", name: "weary" },
      { char: "😫", name: "tired" },
      { char: "🥱", name: "yawn" },
      { char: "😤", name: "triumph", tags: ["steam"] },
      { char: "😡", name: "rage", tags: ["angry"] },
      { char: "😠", name: "angry" },
      { char: "🤬", name: "swearing" },
      { char: "😈", name: "imp", tags: ["devil"] },
      { char: "👿", name: "angry imp" },
      { char: "💀", name: "skull" },
      { char: "💩", name: "poop" },
      { char: "🤡", name: "clown" },
      { char: "👹", name: "ogre" },
      { char: "👺", name: "goblin" },
      { char: "👻", name: "ghost" },
      { char: "👽", name: "alien" },
      { char: "👾", name: "space invader" },
      { char: "🤖", name: "robot" },
      { char: "💯", name: "100", tags: ["hundred", "score"] },
      { char: "💢", name: "anger" },
      { char: "💥", name: "boom" },
      { char: "💫", name: "dizzy stars" },
      { char: "💦", name: "sweat drops" },
      { char: "💨", name: "dash" },
      { char: "🕳️", name: "hole" },
      { char: "💣", name: "bomb" },
      { char: "💬", name: "speech bubble" },
      { char: "💭", name: "thought bubble" },
      { char: "💤", name: "zzz", tags: ["sleep"] },
    ],
  },
  {
    id: "gestures",
    label: "People & gestures",
    emoji: [
      { char: "👋", name: "wave" },
      { char: "🤚", name: "raised back of hand" },
      { char: "🖐️", name: "splayed hand" },
      { char: "✋", name: "raised hand" },
      { char: "🖖", name: "vulcan" },
      { char: "👌", name: "ok hand" },
      { char: "🤌", name: "pinched fingers" },
      { char: "🤏", name: "pinching" },
      { char: "✌️", name: "victory", tags: ["peace"] },
      { char: "🤞", name: "fingers crossed" },
      { char: "🤟", name: "love you" },
      { char: "🤘", name: "rock on" },
      { char: "🤙", name: "call me" },
      { char: "👈", name: "left point" },
      { char: "👉", name: "right point" },
      { char: "👆", name: "up point" },
      { char: "🖕", name: "middle finger" },
      { char: "👇", name: "down point" },
      { char: "☝️", name: "index up" },
      { char: "👍", name: "thumbs up" },
      { char: "👎", name: "thumbs down" },
      { char: "✊", name: "fist" },
      { char: "👊", name: "punch" },
      { char: "🤛", name: "left fist" },
      { char: "🤜", name: "right fist" },
      { char: "👏", name: "clap" },
      { char: "🙌", name: "raised hands", tags: ["praise"] },
      { char: "👐", name: "open hands" },
      { char: "🤲", name: "palms up" },
      { char: "🤝", name: "handshake" },
      { char: "🙏", name: "pray", tags: ["thanks"] },
      { char: "💅", name: "nail polish" },
      { char: "🤳", name: "selfie" },
      { char: "💪", name: "flex", tags: ["strong"] },
      { char: "🦾", name: "robotic arm" },
      { char: "👀", name: "eyes" },
      { char: "👁️", name: "eye" },
      { char: "👅", name: "tongue" },
      { char: "👄", name: "lips" },
      { char: "🧠", name: "brain" },
      { char: "🫀", name: "anatomical heart" },
      { char: "🦴", name: "bone" },
      { char: "👶", name: "baby" },
      { char: "🧒", name: "child" },
      { char: "👦", name: "boy" },
      { char: "👧", name: "girl" },
      { char: "🧑", name: "person" },
      { char: "👨", name: "man" },
      { char: "👩", name: "woman" },
      { char: "🧓", name: "older person" },
      { char: "👴", name: "old man" },
      { char: "👵", name: "old woman" },
      { char: "🙇", name: "bowing" },
      { char: "🤦", name: "facepalm" },
      { char: "🤷", name: "shrug" },
      { char: "💃", name: "dancing" },
      { char: "🕺", name: "man dancing" },
      { char: "🚶", name: "walking" },
      { char: "🏃", name: "running" },
    ],
  },
  {
    id: "nature",
    label: "Animals & nature",
    emoji: [
      { char: "🐶", name: "dog" },
      { char: "🐱", name: "cat" },
      { char: "🐭", name: "mouse" },
      { char: "🐹", name: "hamster" },
      { char: "🐰", name: "rabbit" },
      { char: "🦊", name: "fox" },
      { char: "🐻", name: "bear" },
      { char: "🐼", name: "panda" },
      { char: "🐨", name: "koala" },
      { char: "🐯", name: "tiger" },
      { char: "🦁", name: "lion" },
      { char: "🐮", name: "cow" },
      { char: "🐷", name: "pig" },
      { char: "🐸", name: "frog" },
      { char: "🐵", name: "monkey face" },
      { char: "🙈", name: "see no evil" },
      { char: "🙉", name: "hear no evil" },
      { char: "🙊", name: "speak no evil" },
      { char: "🐒", name: "monkey" },
      { char: "🐔", name: "chicken" },
      { char: "🐧", name: "penguin" },
      { char: "🐦", name: "bird" },
      { char: "🐤", name: "chick" },
      { char: "🦆", name: "duck" },
      { char: "🦅", name: "eagle" },
      { char: "🦉", name: "owl" },
      { char: "🦇", name: "bat" },
      { char: "🐺", name: "wolf" },
      { char: "🐗", name: "boar" },
      { char: "🐴", name: "horse face" },
      { char: "🦄", name: "unicorn" },
      { char: "🐝", name: "bee" },
      { char: "🐛", name: "bug" },
      { char: "🦋", name: "butterfly" },
      { char: "🐌", name: "snail" },
      { char: "🐞", name: "ladybug" },
      { char: "🐢", name: "turtle" },
      { char: "🐍", name: "snake" },
      { char: "🦎", name: "lizard" },
      { char: "🐙", name: "octopus" },
      { char: "🦑", name: "squid" },
      { char: "🦐", name: "shrimp" },
      { char: "🦞", name: "lobster" },
      { char: "🦀", name: "crab" },
      { char: "🐟", name: "fish" },
      { char: "🐬", name: "dolphin" },
      { char: "🐳", name: "whale" },
      { char: "🦈", name: "shark" },
      { char: "🐊", name: "crocodile" },
      { char: "🐅", name: "tiger body" },
      { char: "🐆", name: "leopard" },
      { char: "🦓", name: "zebra" },
      { char: "🦍", name: "gorilla" },
      { char: "🐘", name: "elephant" },
      { char: "🦏", name: "rhino" },
      { char: "🦛", name: "hippo" },
      { char: "🐪", name: "camel" },
      { char: "🐫", name: "two hump camel" },
      { char: "🦒", name: "giraffe" },
      { char: "🦘", name: "kangaroo" },
      { char: "🐎", name: "horse" },
      { char: "🐖", name: "pig body" },
      { char: "🐂", name: "ox" },
      { char: "🐑", name: "sheep" },
      { char: "🐐", name: "goat" },
      { char: "🦌", name: "deer" },
      { char: "🐕", name: "dog body" },
      { char: "🐩", name: "poodle" },
      { char: "🦮", name: "guide dog" },
      { char: "🐈", name: "cat body" },
      { char: "🐓", name: "rooster" },
      { char: "🦃", name: "turkey" },
      { char: "🦚", name: "peacock" },
      { char: "🦜", name: "parrot" },
      { char: "🌳", name: "tree" },
      { char: "🌲", name: "evergreen" },
      { char: "🌴", name: "palm tree" },
      { char: "🌵", name: "cactus" },
      { char: "🌷", name: "tulip" },
      { char: "🌹", name: "rose" },
      { char: "🥀", name: "wilted rose" },
      { char: "🌺", name: "hibiscus" },
      { char: "🌸", name: "cherry blossom" },
      { char: "🌼", name: "blossom" },
      { char: "🌻", name: "sunflower" },
      { char: "☀️", name: "sun" },
      { char: "🌝", name: "full moon face" },
      { char: "🌚", name: "new moon face" },
      { char: "🌙", name: "crescent moon" },
      { char: "⭐", name: "star" },
      { char: "🌟", name: "glowing star" },
      { char: "✨", name: "sparkles" },
      { char: "⚡", name: "lightning" },
      { char: "🔥", name: "fire" },
      { char: "🌈", name: "rainbow" },
      { char: "☁️", name: "cloud" },
      { char: "❄️", name: "snowflake" },
      { char: "☔", name: "umbrella rain" },
      { char: "🌊", name: "wave water" },
    ],
  },
  {
    id: "food",
    label: "Food & drink",
    emoji: [
      { char: "🍎", name: "red apple" },
      { char: "🍐", name: "pear" },
      { char: "🍊", name: "orange" },
      { char: "🍋", name: "lemon" },
      { char: "🍌", name: "banana" },
      { char: "🍉", name: "watermelon" },
      { char: "🍇", name: "grapes" },
      { char: "🍓", name: "strawberry" },
      { char: "🫐", name: "blueberries" },
      { char: "🍈", name: "melon" },
      { char: "🍒", name: "cherries" },
      { char: "🍑", name: "peach" },
      { char: "🥭", name: "mango" },
      { char: "🍍", name: "pineapple" },
      { char: "🥥", name: "coconut" },
      { char: "🥝", name: "kiwi" },
      { char: "🍅", name: "tomato" },
      { char: "🍆", name: "eggplant" },
      { char: "🥑", name: "avocado" },
      { char: "🥦", name: "broccoli" },
      { char: "🥬", name: "leafy green" },
      { char: "🥒", name: "cucumber" },
      { char: "🌶️", name: "hot pepper" },
      { char: "🌽", name: "corn" },
      { char: "🥕", name: "carrot" },
      { char: "🧄", name: "garlic" },
      { char: "🧅", name: "onion" },
      { char: "🥔", name: "potato" },
      { char: "🍠", name: "sweet potato" },
      { char: "🥐", name: "croissant" },
      { char: "🥯", name: "bagel" },
      { char: "🍞", name: "bread" },
      { char: "🥖", name: "baguette" },
      { char: "🥨", name: "pretzel" },
      { char: "🧀", name: "cheese" },
      { char: "🥚", name: "egg" },
      { char: "🍳", name: "fried egg" },
      { char: "🥞", name: "pancakes" },
      { char: "🧇", name: "waffle" },
      { char: "🥓", name: "bacon" },
      { char: "🥩", name: "steak" },
      { char: "🍗", name: "poultry leg" },
      { char: "🍖", name: "meat on bone" },
      { char: "🌭", name: "hotdog" },
      { char: "🍔", name: "burger" },
      { char: "🍟", name: "fries" },
      { char: "🍕", name: "pizza" },
      { char: "🥪", name: "sandwich" },
      { char: "🌮", name: "taco" },
      { char: "🌯", name: "burrito" },
      { char: "🥙", name: "stuffed flatbread" },
      { char: "🍱", name: "bento" },
      { char: "🍲", name: "stew" },
      { char: "🍝", name: "spaghetti" },
      { char: "🍜", name: "ramen" },
      { char: "🍣", name: "sushi" },
      { char: "🍤", name: "fried shrimp" },
      { char: "🍙", name: "rice ball" },
      { char: "🍚", name: "rice" },
      { char: "🥘", name: "shallow pan" },
      { char: "🍢", name: "oden" },
      { char: "🥡", name: "takeout" },
      { char: "🍦", name: "soft ice cream" },
      { char: "🍨", name: "ice cream" },
      { char: "🍧", name: "shaved ice" },
      { char: "🍩", name: "donut" },
      { char: "🍪", name: "cookie" },
      { char: "🎂", name: "birthday cake" },
      { char: "🍰", name: "cake" },
      { char: "🧁", name: "cupcake" },
      { char: "🥧", name: "pie" },
      { char: "🍫", name: "chocolate" },
      { char: "🍬", name: "candy" },
      { char: "🍭", name: "lollipop" },
      { char: "🍯", name: "honey" },
      { char: "🍼", name: "baby bottle" },
      { char: "🥛", name: "milk" },
      { char: "☕", name: "coffee" },
      { char: "🫖", name: "teapot" },
      { char: "🍵", name: "tea" },
      { char: "🍶", name: "sake" },
      { char: "🍾", name: "champagne" },
      { char: "🍷", name: "wine" },
      { char: "🍸", name: "cocktail" },
      { char: "🍹", name: "tropical drink" },
      { char: "🍺", name: "beer" },
      { char: "🍻", name: "clink beers" },
      { char: "🥂", name: "clink glasses" },
      { char: "🥃", name: "tumbler" },
    ],
  },
  {
    id: "activity",
    label: "Activity & objects",
    emoji: [
      { char: "⚽", name: "soccer" },
      { char: "🏀", name: "basketball" },
      { char: "🏈", name: "football" },
      { char: "⚾", name: "baseball" },
      { char: "🥎", name: "softball" },
      { char: "🎾", name: "tennis" },
      { char: "🏐", name: "volleyball" },
      { char: "🏉", name: "rugby" },
      { char: "🥏", name: "frisbee" },
      { char: "🎱", name: "pool 8 ball" },
      { char: "🪀", name: "yo-yo" },
      { char: "🏓", name: "ping pong" },
      { char: "🏸", name: "badminton" },
      { char: "🥅", name: "goal" },
      { char: "🏒", name: "ice hockey" },
      { char: "🏑", name: "field hockey" },
      { char: "🥍", name: "lacrosse" },
      { char: "🏏", name: "cricket" },
      { char: "⛳", name: "golf" },
      { char: "🏹", name: "bow and arrow" },
      { char: "🎣", name: "fishing" },
      { char: "🥊", name: "boxing" },
      { char: "🥋", name: "martial arts" },
      { char: "🎽", name: "running shirt" },
      { char: "🛹", name: "skateboard" },
      { char: "🛼", name: "roller skate" },
      { char: "🛷", name: "sled" },
      { char: "⛸️", name: "ice skate" },
      { char: "🎿", name: "ski" },
      { char: "🏂", name: "snowboarder" },
      { char: "🪂", name: "parachute" },
      { char: "🏋️", name: "weight lifter" },
      { char: "🤺", name: "fencer" },
      { char: "🤾", name: "handball" },
      { char: "🏌️", name: "golfer" },
      { char: "🏇", name: "horse racing" },
      { char: "🧘", name: "yoga" },
      { char: "🏄", name: "surfer" },
      { char: "🏊", name: "swimmer" },
      { char: "🚴", name: "cyclist" },
      { char: "🎮", name: "video game" },
      { char: "🕹️", name: "joystick" },
      { char: "🎰", name: "slot machine" },
      { char: "🎲", name: "die" },
      { char: "🧩", name: "puzzle" },
      { char: "♟️", name: "chess pawn" },
      { char: "🎯", name: "bullseye" },
      { char: "🎳", name: "bowling" },
      { char: "🎤", name: "microphone" },
      { char: "🎧", name: "headphones" },
      { char: "🎷", name: "saxophone" },
      { char: "🎸", name: "guitar" },
      { char: "🎹", name: "piano" },
      { char: "🎺", name: "trumpet" },
      { char: "🎻", name: "violin" },
      { char: "🥁", name: "drum" },
      { char: "🪕", name: "banjo" },
      { char: "🎬", name: "clapper", tags: ["movie"] },
      { char: "🎨", name: "artist palette" },
      { char: "✏️", name: "pencil" },
      { char: "📚", name: "books" },
      { char: "📖", name: "open book" },
      { char: "📝", name: "memo" },
      { char: "🔬", name: "microscope" },
      { char: "🔭", name: "telescope" },
      { char: "💡", name: "lightbulb", tags: ["idea"] },
      { char: "🔑", name: "key" },
      { char: "🔒", name: "locked" },
      { char: "🔓", name: "unlocked" },
      { char: "⏰", name: "alarm" },
      { char: "⏳", name: "hourglass" },
      { char: "💎", name: "gem" },
      { char: "💰", name: "money bag" },
      { char: "💵", name: "dollar" },
      { char: "💳", name: "credit card" },
      { char: "🎁", name: "gift" },
      { char: "🎉", name: "party popper" },
      { char: "🎊", name: "confetti" },
      { char: "🎈", name: "balloon" },
      { char: "🎀", name: "ribbon" },
      { char: "🎃", name: "jack o lantern" },
      { char: "🎄", name: "christmas tree" },
      { char: "🪅", name: "piñata" },
      { char: "📷", name: "camera" },
      { char: "📹", name: "video camera" },
      { char: "📺", name: "tv" },
      { char: "📱", name: "phone" },
      { char: "💻", name: "laptop" },
      { char: "🖥️", name: "desktop" },
      { char: "⌨️", name: "keyboard" },
      { char: "🖱️", name: "mouse computer" },
      { char: "💾", name: "floppy disk", tags: ["save"] },
      { char: "💿", name: "cd" },
      { char: "📀", name: "dvd" },
    ],
  },
  {
    id: "travel",
    label: "Travel & places",
    emoji: [
      { char: "🚗", name: "car" },
      { char: "🚕", name: "taxi" },
      { char: "🚙", name: "suv" },
      { char: "🚌", name: "bus" },
      { char: "🚎", name: "trolley" },
      { char: "🏎️", name: "race car" },
      { char: "🚓", name: "police car" },
      { char: "🚑", name: "ambulance" },
      { char: "🚒", name: "fire engine" },
      { char: "🚐", name: "minibus" },
      { char: "🛻", name: "pickup" },
      { char: "🚚", name: "truck" },
      { char: "🚛", name: "semi" },
      { char: "🏍️", name: "motorcycle" },
      { char: "🛵", name: "scooter" },
      { char: "🚲", name: "bike" },
      { char: "🛴", name: "kick scooter" },
      { char: "🚨", name: "police light" },
      { char: "🚔", name: "police car oncoming" },
      { char: "🚍", name: "bus oncoming" },
      { char: "🚖", name: "taxi oncoming" },
      { char: "🚆", name: "train" },
      { char: "🚇", name: "metro" },
      { char: "🚊", name: "tram" },
      { char: "🚉", name: "station" },
      { char: "✈️", name: "plane" },
      { char: "🛫", name: "departing" },
      { char: "🛬", name: "landing" },
      { char: "🛩️", name: "small plane" },
      { char: "🚀", name: "rocket" },
      { char: "🛸", name: "ufo" },
      { char: "🚁", name: "helicopter" },
      { char: "⛵", name: "sailboat" },
      { char: "🚤", name: "speedboat" },
      { char: "🛥️", name: "motor boat" },
      { char: "🛳️", name: "passenger ship" },
      { char: "⛴️", name: "ferry" },
      { char: "🚢", name: "ship" },
      { char: "⚓", name: "anchor" },
      { char: "🏠", name: "house" },
      { char: "🏡", name: "house garden" },
      { char: "🏢", name: "office" },
      { char: "🏬", name: "department store" },
      { char: "🏣", name: "post office" },
      { char: "🏥", name: "hospital" },
      { char: "🏦", name: "bank" },
      { char: "🏨", name: "hotel" },
      { char: "🏪", name: "convenience" },
      { char: "🏫", name: "school" },
      { char: "🏛️", name: "classical building" },
      { char: "⛪", name: "church" },
      { char: "🕌", name: "mosque" },
      { char: "🕍", name: "synagogue" },
      { char: "🛕", name: "temple" },
      { char: "🏯", name: "castle japan" },
      { char: "🏰", name: "castle" },
      { char: "🗼", name: "tokyo tower" },
      { char: "🗽", name: "statue of liberty" },
      { char: "⛩️", name: "shrine" },
      { char: "🌁", name: "foggy city" },
      { char: "🌃", name: "night stars" },
      { char: "🌄", name: "sunrise mountains" },
      { char: "🌅", name: "sunrise" },
      { char: "🌆", name: "sunset city" },
      { char: "🌇", name: "sunset" },
      { char: "🌉", name: "bridge night" },
      { char: "🌋", name: "volcano" },
      { char: "🗻", name: "mount fuji" },
      { char: "🏔️", name: "snowy mountain" },
      { char: "⛰️", name: "mountain" },
      { char: "🏖️", name: "beach" },
      { char: "🏝️", name: "desert island" },
      { char: "🌍", name: "earth africa" },
      { char: "🌎", name: "earth americas" },
      { char: "🌏", name: "earth asia" },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    emoji: [
      { char: "❤️", name: "red heart", tags: ["love"] },
      { char: "🧡", name: "orange heart" },
      { char: "💛", name: "yellow heart" },
      { char: "💚", name: "green heart" },
      { char: "💙", name: "blue heart" },
      { char: "💜", name: "purple heart" },
      { char: "🖤", name: "black heart" },
      { char: "🤍", name: "white heart" },
      { char: "🤎", name: "brown heart" },
      { char: "💔", name: "broken heart" },
      { char: "❣️", name: "heart exclamation" },
      { char: "💕", name: "two hearts" },
      { char: "💞", name: "revolving hearts" },
      { char: "💓", name: "beating heart" },
      { char: "💗", name: "growing heart" },
      { char: "💖", name: "sparkling heart" },
      { char: "💘", name: "heart arrow" },
      { char: "💝", name: "gift heart" },
      { char: "♥️", name: "spade heart" },
      { char: "♠️", name: "spades" },
      { char: "♣️", name: "clubs" },
      { char: "♦️", name: "diamonds" },
      { char: "☮️", name: "peace" },
      { char: "✝️", name: "cross" },
      { char: "☪️", name: "star and crescent" },
      { char: "☸️", name: "dharma" },
      { char: "✡️", name: "star of david" },
      { char: "☯️", name: "yin yang" },
      { char: "🕉️", name: "om" },
      { char: "☦️", name: "orthodox cross" },
      { char: "⚛️", name: "atom" },
      { char: "☢️", name: "radioactive" },
      { char: "☣️", name: "biohazard" },
      { char: "♻️", name: "recycle" },
      { char: "🆗", name: "ok square" },
      { char: "🆕", name: "new" },
      { char: "🆒", name: "cool" },
      { char: "🆓", name: "free" },
      { char: "🆙", name: "up" },
      { char: "🔝", name: "top" },
      { char: "🔚", name: "end" },
      { char: "🔛", name: "on" },
      { char: "🔙", name: "back" },
      { char: "🔜", name: "soon" },
      { char: "✅", name: "check" },
      { char: "❌", name: "cross mark", tags: ["wrong"] },
      { char: "⭕", name: "circle red" },
      { char: "🚫", name: "no entry" },
      { char: "❗", name: "exclamation" },
      { char: "❓", name: "question" },
      { char: "❕", name: "white exclamation" },
      { char: "❔", name: "white question" },
      { char: "‼️", name: "double exclamation" },
      { char: "⚠️", name: "warning" },
      { char: "🚸", name: "children crossing" },
      { char: "⚜️", name: "fleur de lis" },
      { char: "🔱", name: "trident" },
      { char: "📛", name: "name badge" },
      { char: "🔰", name: "japanese symbol for beginner" },
      { char: "♈", name: "aries" },
      { char: "♉", name: "taurus" },
      { char: "♊", name: "gemini" },
      { char: "♋", name: "cancer" },
      { char: "♌", name: "leo" },
      { char: "♍", name: "virgo" },
      { char: "♎", name: "libra" },
      { char: "♏", name: "scorpio" },
      { char: "♐", name: "sagittarius" },
      { char: "♑", name: "capricorn" },
      { char: "♒", name: "aquarius" },
      { char: "♓", name: "pisces" },
      { char: "⛎", name: "ophiuchus" },
      { char: "🔯", name: "six pointed star" },
      { char: "❇️", name: "sparkle" },
      { char: "✳️", name: "eight spoked asterisk" },
      { char: "✴️", name: "eight pointed star" },
      { char: "🌐", name: "globe meridians" },
      { char: "🔘", name: "radio button" },
      { char: "🔲", name: "black square" },
      { char: "🔳", name: "white square" },
      { char: "⚫", name: "black circle" },
      { char: "⚪", name: "white circle" },
      { char: "🟢", name: "green circle" },
      { char: "🟡", name: "yellow circle" },
      { char: "🟠", name: "orange circle" },
      { char: "🔴", name: "red circle" },
      { char: "🔵", name: "blue circle" },
      { char: "🟣", name: "purple circle" },
      { char: "🟤", name: "brown circle" },
      { char: "⬛", name: "black large square" },
      { char: "⬜", name: "white large square" },
      { char: "🟥", name: "red square" },
      { char: "🟧", name: "orange square" },
      { char: "🟨", name: "yellow square" },
      { char: "🟩", name: "green square" },
      { char: "🟦", name: "blue square" },
      { char: "🟪", name: "purple square" },
      { char: "🟫", name: "brown square" },
    ],
  },
];

/**
 * Flat index of every catalog entry for the global search box. Built
 * once at module load so the picker doesn't re-iterate the categorized
 * structure on every keystroke. Search matches against `name` and any
 * `tags`; results are sorted by category order then by name order.
 */
export const UNICODE_EMOJI_FLAT: ReadonlyArray<UnicodeEmoji & { categoryId: string }> = (() => {
  const out: Array<UnicodeEmoji & { categoryId: string }> = [];
  for (const cat of UNICODE_EMOJI_CATEGORIES) {
    for (const e of cat.emoji) {
      out.push({ ...e, categoryId: cat.id });
    }
  }
  return out;
})();

/** Char → name lookup. Used by the reaction renderer to compose a
 *  human-readable tooltip ("smile") for the Unicode emoji chip. Falls
 *  back to the raw glyph when the catalog doesn't carry the entry —
 *  arbitrary Unicode reactions can still come in via paste / OS picker
 *  even though the matrix only enumerates the curated subset. */
const UNICODE_EMOJI_NAME_BY_CHAR: ReadonlyMap<string, string> = (() => {
  const m = new Map<string, string>();
  for (const e of UNICODE_EMOJI_FLAT) m.set(e.char, e.name);
  return m;
})();

export function lookupUnicodeEmojiName(char: string): string | null {
  return UNICODE_EMOJI_NAME_BY_CHAR.get(char) ?? null;
}
